name: ArmenianBible
options:
  bundleIdPrefix: com.samvel.armenianbible
targets:
  ArmenianBible:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleName: ArmenianBible
        CFBundleDisplayName: ArmenianBible
        CFBundleIdentifier: com.samvel.armenianbible
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: ArmenianBible
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: LaunchImage
          UIImageRespectsSafetyMargins: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait

    settings:
      base:
        SWIFT_VERSION: "5.9"
        PRODUCT_NAME: ArmenianBible
        PRODUCT_BUNDLE_IDENTIFIER: com.samvel.armenianbible
        GENERATE_INFOPLIST_FILE: "NO"
        DEVELOPMENT_TEAM: "V7J345DY58"
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_PRIMARY_APPICON_SET_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "YES"
    dependencies:
      - sdk: libsqlite3.dylib
