import Foundation

extension QuizDatabase {
    // // MARK: - РАСШИРЕНИЕ
    static let questionsExtra: [QuizQuestion] = [
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ էր առաջին քրիստոնյա նահատակը, որին քարկոծեցին հավատքի համար։",
            questionRu: "Кто был первым христианским мучеником (первомучеником), побитым камнями за проповедь Христа?",
            questionEn: "Who was the first Christian martyr (protomartyr) stoned for his faith?",
            optionsHy: ["Սուրբ Ստեփանոս Նախավկան", "Սուրբ Պողոսը", "Սուրբ Պետրոսը", "Սուրբ Բառնաբասը"],
            optionsRu: ["Святой архидиакон Стефан", "Святой Павел", "Святой Петр", "Святой Варнава"],
            optionsEn: ["Saint Stephen the Protomartyr", "Saint Paul", "Saint Peter", "Saint Barnabas"],
            correctAnswerIndex: 0,
            explanationHy: "Ստեփանոս Նախավկան աղոթեց իրեն քարկոծողների համար. «Տե՛ր, այս մեղքը դրանց վրա մի՛ դիր» (Գործք 7:60)։",
            explanationRu: "Святой Стефан молился за своих мучителей: «Господи! не вмени им греха сего» (Деяния 7:60).",
            explanationEn: "Saint Stephen prayed for his executioners: «Lord, do not hold this sin against them» (Acts 7:60).",
            verseRefHy: "Գործք 7:54-60",
            verseRefRu: "Деяния 7:54-60",
            verseRefEn: "Acts 7:54-60"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ի՞նչ պատահեց Սողոսին (ապագա Պողոս առաքյալին) Դամասկոսի ճանապարհին։",
            questionRu: "Что произошло с Савлом (будущим апостолом Павлом) по дороге в Дамаск?",
            questionEn: "What happened to Saul (the future Apostle Paul) on the road to Damascus?",
            optionsHy: ["Երկնքից լույս փայլեց և Հիսուս կանչեց նրան", "Նա նավաբեկության ենթարկվեց", "Նա տեսավ հրեշտակ Գաբրիելին", "Նա հանդիպեց Պետրոս առաքյալին"],
            optionsRu: ["Его осиял небесный свет и Христос призвал его", "Он потерпел кораблекрушение", "Ему явился архангел Гавриил", "Он встретил апостола Петра"],
            optionsEn: ["A heavenly light shone and Jesus called him", "He was shipwrecked", "Archangel Gabriel appeared to him", "He met Apostle Peter"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուս հարցրեց. «Սավո՛ւղ, Սավո՛ւղ, ինչո՞ւ ես ինձ հալածում» (Գործք 9:4)։",
            explanationRu: "Господь обратился к нему: «Савл, Савл! что ты гонишь Меня?» (Деяния 9:4).",
            explanationEn: "Jesus called out: «Saul, Saul, why do you persecute me?» (Acts 9:4).",
            verseRefHy: "Գործք 9:1-9",
            verseRefRu: "Деяния 9:1-9",
            verseRefEn: "Acts 9:1-9"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Որո՞նք են Սուրբ Հոգու պտուղները՝ ըստ Գաղատացիս թղթի։",
            questionRu: "Какие добродетели апостол Павел называет «плодами Духа» в Послании к Галатам?",
            questionEn: "Which virtues does Paul list as the «fruit of the Spirit» in Galatians?",
            optionsHy: [
                "Սեր, խնդություն, խաղաղություն, համբերատարություն",
                "Հարստություն, իշխանություն, փառք",
                "Զայրույթ, խանդ, հպարտություն",
                "Լռություն, միայնություն, վախ"
            ],
            optionsRu: [
                "Любовь, радость, мир, долготерпение, благость, вера",
                "Богатство, земная власть, слава",
                "Гнев, соперничество, гордость",
                "Молчание, одиночество, страх"
            ],
            optionsEn: [
                "Love, joy, peace, forbearance, kindness, goodness, faithfulness",
                "Wealth, earthly power, fame",
                "Anger, jealousy, pride",
                "Silence, solitude, fear"
            ],
            correctAnswerIndex: 0,
            explanationHy: "«Հոգու պտուղն է՝ սեր, խնդություն, խաղաղություն, երկայնամտություն...» (Գաղատացիս 5:22)։",
            explanationRu: "«Плод же духа: любовь, радость, мир, долготерпение, благость, милосердие, вера» (Гал 5:22).",
            explanationEn: "«The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness» (Gal 5:22).",
            verseRefHy: "Գաղատացիս 5:22-23",
            verseRefRu: "Галатам 5:22-23",
            verseRefEn: "Galatians 5:22-23"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ինչի՞ հետ է համեմատում Պողոս առաքյալը հավատքը Աստծո սպառազինության մեջ (Եփեսացիս 6)։",
            questionRu: "С каким предметом духовного всеоружия сравнивает веру апостол Павел в Послании к Ефесянам?",
            questionEn: "With which piece of spiritual armor does Paul compare faith in Ephesians 6?",
            optionsHy: ["Վահանի հետ (Հավատքի վահան)", "Սաղավարտի հետ", "Սրի հետ", "Գոտու հետ"],
            optionsRu: ["Со щитом («Щит веры»)", "Со шлемом", "С мечом", "С поясом"],
            optionsEn: ["With a shield («Shield of faith»)", "With a helmet", "With a sword", "With a belt"],
            correctAnswerIndex: 0,
            explanationHy: "«Ամեն ինչից առաջ վերցրե՛ք հավատքի վահանը, որով կկարողանաք հանգցնել չարի բոլոր բոցավառ նետերը» (Եփես. 6:16)։",
            explanationRu: "«А паче всего возьмите щит веры, которым возможете угасить все раскаленные стрелы лукавого» (Еф 6:16).",
            explanationEn: "«Take up the shield of faith, with which you can extinguish all the flaming arrows of the evil one» (Eph 6:16).",
            verseRefHy: "Եփեսացիս 6:16",
            verseRefRu: "Ефесянам 6:16",
            verseRefEn: "Ephesians 6:16"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ո՞ր կղզում էր աքսորված Հովհաննես առաքյալը, երբ գրեց Հայտնության գիրքը։",
            questionRu: "На каком острове находился в ссылке святой апостол Иоанн Богослов, когда получил Откровение?",
            questionEn: "On which island was the Apostle John exiled when he wrote the Book of Revelation?",
            optionsHy: ["Պատմոս կղզում", "Կրետե կղզում", "Կիպրոսում", "Մալթայում"],
            optionsRu: ["На острове Патмос", "На острове Крит", "На Кипре", "На Мальте"],
            optionsEn: ["On the Island of Patmos", "On Crete", "On Cyprus", "On Malta"],
            correctAnswerIndex: 0,
            explanationHy: "«Ես՝ Հովհաննեսս... գտնվում էի Պատմոս կոչվող կղզում Աստծո խոսքի համար» (Հայտն. 1:9)։",
            explanationRu: "«Я, Иоанн... был на острове, называемом Патмос, за слово Божие» (Откр 1:9).",
            explanationEn: "«I, John... was on the island of Patmos because of the word of God» (Rev 1:9).",
            verseRefHy: "Հայտնություն 1:9",
            verseRefRu: "Откровение 1:9",
            verseRefEn: "Revelation 1:9"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ էր առաջին հեթանոս հարյուրապետը, որը մկրտվեց Պետրոս առաքյալի կողմից։",
            questionRu: "Кто был первым языческим римским сотником, принявшим крещение от апостола Петра?",
            questionEn: "Who was the first Gentile centurion baptized by the Apostle Peter?",
            optionsHy: ["Կոռնելիոսը", "Հուլիոսը", "Լոնգինոսը", "Պիղատոսը"],
            optionsRu: ["Корнилий сотник", "Сотник Юлий", "Сотник Лонгин", "Понтий Пилат"],
            optionsEn: ["Cornelius the Centurion", "Centurion Julius", "Centurion Longinus", "Pontius Pilate"],
            correctAnswerIndex: 0,
            explanationHy: "Կոռնելիոսը բարեպաշտ և ողորմած մարդ էր, որի տանը Սուրբ Հոգին իջավ հեթանոսների վրա (Գործք 10)։",
            explanationRu: "Корнилий был благочестивым воином в Кесарии, на дом которого сошел Святой Дух (Деяния 10).",
            explanationEn: "Cornelius was a devout centurion in Caesarea whose conversion opened the door to the Gentiles (Acts 10).",
            verseRefHy: "Գործք 10:1-48",
            verseRefRu: "Деяния 10:1-48",
            verseRefEn: "Acts 10:1-48"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ինչպե՞ս է սահմանում Եբրայեցիներին ուղղված թուղթը Հավատքը (Եբր. 11:1)։",
            questionRu: "Как определяется вера в Послании к Евреям (Евр. 11:1)?",
            questionEn: "How is faith defined in Hebrews 11:1?",
            optionsHy: [
                "Հույս ունեցած բաների հաստատություն և չերևացող բաների ապացույց",
                "Միայն մտավոր համաձայնություն",
                "Երկրային հարստության ակնկալիք",
                "Առանց գործերի զգացմունք"
            ],
            optionsRu: [
                "Осуществление ожидаемого и уверенность в невидимом",
                "Простое знание фактов о Боге",
                "Ожидание материального благополучия",
                "Эмоциональное переживание без дел"
            ],
            optionsEn: [
                "Confidence in what we hope for and assurance about what we do not see",
                "Simple mental knowledge",
                "Expectation of earthly wealth",
                "Feelings without works"
            ],
            correctAnswerIndex: 0,
            explanationHy: "«Հավատքը հուսացած բաների հաստատությունն է և չերևացող բաների ապացույցը» (Եբրայեցիս 11:1)։",
            explanationRu: "«Вера же есть осуществление ожидаемого и уверенность в невидимом» (Евр 11:1).",
            explanationEn: "«Now faith is confidence in what we hope for and assurance about what we do not see» (Heb 11:1).",
            verseRefHy: "Եբրայեցիս 11:1",
            verseRefRu: "Евреям 11:1",
            verseRefEn: "Hebrews 11:1"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ինչի՞ հետ է համեմատում Հակոբոս առաքյալը մարդու լեզուն (Հակոբոս 3)։",
            questionRu: "С чем сравнивает человеческий язык апостол Иаков в своем послании?",
            questionEn: "What does James compare the human tongue to in James 3?",
            optionsHy: ["Փոքր կրակի և նավի ղեկի հետ", "Սրածայր դաշույնի հետ", "Հոսող գետի հետ", "Ծաղկած ծառի հետ"],
            optionsRu: ["С небольшим огнем и корабельным рулем", "С острым мечом", "С бурным потоком", "С цветущим деревом"],
            optionsEn: ["With a small spark and a ship's rudder", "With a sharp dagger", "With a flowing river", "With a blooming tree"],
            correctAnswerIndex: 0,
            explanationHy: "Լեզուն փոքր անդամ է, բայց կարող է մեծ անտառ հրդեհել և ղեկավարել ամբողջ մարմինը (Հակոբոս 3:4-5)։",
            explanationRu: "Язык — малый член, но держит руль корабля и может зажечь великий лес (Иак 3:4-5).",
            explanationEn: "The tongue is a small part of the body, but it makes great boasts like a small spark setting a forest on fire (James 3:4-5).",
            verseRefHy: "Հակոբոս 3:2-8",
            verseRefRu: "Иакова 3:2-8",
            verseRefEn: "James 3:2-8"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ո՞ր քաղաքի Արեոպագոսում Պողոս առաքյալը քարոզեց «Անծանոթ Աստծո» մասին։",
            questionRu: "В каком знаменитом городе на холме Ареопаг апостол Павел проповедовал о «Неведомом Боге»?",
            questionEn: "In which city on Mars Hill (Areopagus) did Paul preach about the «Unknown God»?",
            optionsHy: ["Աթենքում", "Հռոմում", "Կորնթոսում", "Եփեսոսում"],
            optionsRu: ["В Афинах", "В Риме", "В Коринфе", "В Ефесе"],
            optionsEn: ["In Athens", "In Rome", "In Corinth", "In Ephesus"],
            correctAnswerIndex: 0,
            explanationHy: "Պողոսը տեսավ զոհասեղան «Անծանոթ Աստծուն» գրությամբ և Աթենքի փիլիսոփաներին ավետեց Կենդանի Տիրոջը (Գործք 17:23)։",
            explanationRu: "Апостол Павел благовествовал греческим философам об Истинном Создателе у жертвенника «Неведомому Богу» (Деяния 17:23).",
            explanationEn: "Paul addressed the Athenian philosophers at the Areopagus regarding their altar to an «Unknown God» (Acts 17:23).",
            verseRefHy: "Գործք 17:22-31",
            verseRefRu: "Деяния 17:22-31",
            verseRefEn: "Acts 17:22-31"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ո՞վ էր Պողոս առաքյալի հավատարիմ աշակերտը, որին նա անվանեց «հարազատ որդի հավատքի մեջ»։",
            questionRu: "Кого апостол Павел называл своим «истинным сыном по вере» и посвятил ему два пастырских послания?",
            questionEn: "Whom did Paul call his «true son in the faith» and dedicate two pastoral epistles to?",
            optionsHy: ["Տիմոթեոսին", "Տիտոսին", "Փիլիմոնին", "Սիղային"],
            optionsRu: ["Тимофея", "Тита", "Филимона", "Силу"],
            optionsEn: ["Timothy", "Titus", "Philemon", "Silas"],
            correctAnswerIndex: 0,
            explanationHy: "Տիմոթեոսը մանկուց դաստիարակվել էր Սուրբ Գրքով իր մոր՝ Եվնիկեի և տատի՝ Լոիդայի կողմից (Բ Տիմ. 1:5)։",
            explanationRu: "Юный Тимофей с детства наставлялся в Писании матерью Евникой и бабушкой Лоидой (2 Тим 1:5).",
            explanationEn: "Timothy was nurtured in faith by his mother Eunice and grandmother Lois (2 Tim 1:5).",
            verseRefHy: "Ա Տիմոթեոս 1:2",
            verseRefRu: "1 Тимофею 1:2",
            verseRefEn: "1 Timothy 1:2"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ի՞նչ խորհրդավոր անուն ունի Երկնային Քաղաքը Հայտնության գրքի 21-րդ գլխում։",
            questionRu: "Как называется Небесный Град святости в 21-й главе Откровения Иоанна Богослова?",
            questionEn: "What is the name of the holy heavenly city in Revelation 21?",
            optionsHy: ["Նոր Երուսաղեմ", "Նոր Սիոն", "Եդեմի Պարտեզ", "Արարատ"],
            optionsRu: ["Новый Иерусалим", "Новый Сион", "Сад Эдемский", "Гора Арарат"],
            optionsEn: ["New Jerusalem", "New Zion", "Garden of Eden", "Mount Ararat"],
            correctAnswerIndex: 0,
            explanationHy: "«Եվ տեսա Սուրբ Քաղաքը՝ Նոր Երուսաղեմը, որ իջնում էր երկնքից՝ Աստծո մոտից» (Հայտն. 21:2)։",
            explanationRu: "«И я, Иоанн, увидел святый город Иерусалим, новый, сходящий от Бога с неба» (Откр 21:2).",
            explanationEn: "«I saw the Holy City, the new Jerusalem, coming down out of heaven from God» (Rev 21:2).",
            verseRefHy: "Հայտնություն 21:1-4",
            verseRefRu: "Откровение 21:1-4",
            verseRefEn: "Revelation 21:1-4"
        ),

        // =========================================================================
        // MARK: - РАСШИРЕНИЕ 2: АРМЯНСКАЯ ЦЕРКОВЬ И СВЯТЫЕ (CHURCH HISTORY EXPANSION)
        // =========================================================================
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞վ ստեղծեց հայոց գրերը 405 թվականին՝ Աստվածաշունչը թարգմանելու համար։",
            questionRu: "Кто создал армянский алфавит в 405 году для перевода Священного Писания?",
            questionEn: "Who created the Armenian alphabet in 405 AD to translate the Holy Bible?",
            optionsHy: ["Սուրբ Մեսրոպ Մաշտոցը", "Սուրբ Սահակ Պարթևը", "Մովսես Խորենացին", "Եզնիկ Կողբացին"],
            optionsRu: ["Святой Месроп Маштоц", "Святой Саак Партев", "Мовсес Хоренаци", "Езник Кохбаци"],
            optionsEn: ["Saint Mesrop Mashtots", "Saint Sahak Partev", "Movses Khorenatsi", "Yeznik of Koghb"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Մեսրոպ Մաշտոցը աստվածատուր տեսիլքով ստեղծեց 36 հայկական տառերը 405 թվականին։",
            explanationRu: "Святой Месроп Маштоц в 405 году создал 36 армянских букв, начав Золотой Век письменности.",
            explanationEn: "Saint Mesrop Mashtots created the 36 Armenian letters in 405 AD through divine inspiration.",
            verseRefHy: "Կորյուն, «Վարք Մաշտոցի»",
            verseRefRu: "Корюн, «Житие Маштоца»",
            verseRefEn: "Koryun, The Life of Mashtots"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞րն է հայերեն թարգմանված առաջին նախադասությունը պատմության մեջ։",
            questionRu: "Какое первое предложение в истории было написано и переведено на армянский язык?",
            questionEn: "What was the very first sentence translated and written in the Armenian language?",
            optionsHy: [
                "«Ճանաչել զիմաստութիւն և զխրատ, իմանալ զբանս հանճարոյ» (Առակաց 1:2)",
                "«Սկզբումն էր Բանը»",
                "«Հայր մեր, որ յերկինս ես»",
                "«Տերն իմ հովիվն է»"
            ],
            optionsRu: [
                "«Познать мудрость и наставление, понять изречения разума» (Притчи 1:2)",
                "«В начале было Слово»",
                "«Отче наш, сущий на небесах»",
                "«Господь — Пастырь мой»"
            ],
            optionsEn: [
                "«To know wisdom and instruction, to perceive the words of understanding» (Proverbs 1:2)",
                "«In the beginning was the Word»",
                "«Our Father who art in heaven»",
                "«The Lord is my shepherd»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Մեսրոպ Մաշտոցը թարգմանությունը սկսեց Սողոմոնի Առակներից՝ «Ճանաչել զիմաստութիւն և զխրատ...»։",
            explanationRu: "Первыми армянскими словами стали стихи из Притчей Соломона (Притчи 1:2).",
            explanationEn: "The translation began with Proverbs 1:2: «To know wisdom and instruction...».",
            verseRefHy: "Առակաց 1:2",
            verseRefRu: "Притчи 1:2",
            verseRefEn: "Proverbs 1:2"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ինչպե՞ս են անվանում հայերեն Աստվածաշնչի թարգմանությունը համաշխարհային մշակույթում։",
            questionRu: "Какое почетное звание носит армянский перевод Библии V века в мировом богословии?",
            questionEn: "What honorary title is given to the 5th-century Armenian translation of the Bible?",
            optionsHy: ["«Թարգմանությունների Թագուհի»", "«Արևելքի Մարգարիտ»", "«Ոսկե Մատյան»", "«Սրբության Աղբյուր»"],
            optionsRu: ["«Царица переводов» (Queen of Translations)", "«Жемчужина Востока»", "«Золотая Книга»", "«Источник Святости»"],
            optionsEn: ["«Queen of the Translations»", "«Pearl of the Orient»", "«Golden Book»", "«Fountain of Holiness»"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Սահակ Պարթևի և Մեսրոպ Մաշտոցի թարգմանությունն իր բացառիկ ճշգրտությամբ կոչվեց «Թարգմանությունների Թագուհի»։",
            explanationRu: "За непревзойденное изящество и точность армянскую Библию именуют «Царицей переводов».",
            explanationEn: "European scholars named the Armenian 5th-century version the «Queen of Translations» for its accuracy.",
            verseRefHy: "Ոսկեդար (V դար)",
            verseRefRu: "Золотой Век (V век)",
            verseRefEn: "Golden Age (5th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Քանի՞ տարի անցկացրեց Սուրբ Գրիգոր Լուսավորիչը Խոր Վիրապի խոր փոսում։",
            questionRu: "Сколько лет святой Григорий Просветитель провел в заточении в темнице Хор Вирап?",
            questionEn: "How many years did Saint Gregory the Illuminator spend imprisoned in Khor Virap?",
            optionsHy: ["13 տարի", "7 տարի", "40 օր", "3 տարի"],
            optionsRu: ["13 лет", "7 лет", "40 дней", "3 года"],
            optionsEn: ["13 years", "7 years", "40 days", "3 years"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Գրիգորը 13 տարի մնաց Խոր Վիրապի վիհում՝ աղոթքով և բարեպաշտ կնոջ գաղտնի օգնությամբ պահպանվելով։",
            explanationRu: "Святой Григорий 13 лет молился в глубокой яме Хор Вирапа, пока не исцелил царя Трдата III.",
            explanationEn: "Saint Gregory endured 13 years of imprisonment in the pit of Khor Virap before baptizing King Trdat III.",
            verseRefHy: "Ագաթանգեղոս (IV դար)",
            verseRefRu: "Агафангел (IV век)",
            verseRefEn: "Agathangelos (4th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞վ է հայտնի որպես «Հայոց Պատմահայր» (Քերթողահայր)։",
            questionRu: "Кто вошел в историю как «Отец армянской историографии» (Патмахайр)?",
            questionEn: "Who is celebrated as the «Father of Armenian History» (Patmahayr)?",
            optionsHy: ["Սուրբ Մովսես Խորենացին", "Եղիշեն", "Ղազար Փարպեցին", "Փավստոս Բուզանդը"],
            optionsRu: ["Святой Мовсес Хоренаци", "Егише", "Лазарь Парпеци", "Фавстос Бузанд"],
            optionsEn: ["Saint Movses Khorenatsi", "Yeghishe", "Ghazar Parpetsi", "Pavstos Buzand"],
            correctAnswerIndex: 0,
            explanationHy: "Մովսես Խորենացին 5-րդ դարում գրեց «Հայոց Պատմություն» հիմնարար աշխատությունը՝ սկսելով արարչագործությունից։",
            explanationRu: "Святой Мовсес Хоренаци в V веке создал монументальную «Историю Армении».",
            explanationEn: "Movses Khorenatsi wrote the foundational «History of Armenia» in the 5th century.",
            verseRefHy: "Մովսես Խորենացի, «Հայոց Պատմություն»",
            verseRefRu: "Мовсес Хоренаци, «История Армении»",
            verseRefEn: "Movses Khorenatsi, History of the Armenians"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞ր միջնադարյան հռչակավոր վանքում և համալսարանում էր գործում Սուրբ Գրիգոր Տաթևացին։",
            questionRu: "В каком великом средневековом монастыре и университете творил святой Григор Татеваци?",
            questionEn: "In which renowned medieval monastery and university did Saint Gregory of Tatev teach?",
            optionsHy: ["Տաթևի Վանքում", "Սանահինում", "Գեղարդում", "Հաղպատում"],
            optionsRu: ["В Татевском монастыре", "В Санаине", "В Гегарде", "В Ахпате"],
            optionsEn: ["In Tatev Monastery", "In Sanahin", "In Geghard", "In Haghpat"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Գրիգոր Տաթևացին 14-րդ դարում Տաթևի համալսարանի մեծ րաբունապետն ու աստվածաբանն էր։",
            explanationRu: "Святой Григор Татеваци (XIV век) был выдающимся ректором Татевского университета и автором «Книги вопрошений».",
            explanationEn: "Saint Gregory of Tatev led the famous University of Tatev in the 14th century.",
            verseRefHy: "Տաթևի Համալսարան (XIV դար)",
            verseRefRu: "Татевский Университет (XIV век)",
            verseRefEn: "University of Tatev (14th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Քանի՞ Տաղավար (Գլխավոր Մեծ) տոներ ունի Հայ Առաքելական Եկեղեցին։",
            questionRu: "Сколько Великих (Главных Господских) праздников — Тагаваронк — отмечает Армянская Церковь?",
            questionEn: "How many Major Tabernacle Feasts (Daghavar Feasts) does the Armenian Church celebrate?",
            optionsHy: ["5 Տաղավար տոն", "7 տոն", "12 տոն", "3 տոն"],
            optionsRu: ["5 праздников (Тагаваронк)", "7 праздников", "12 праздников", "3 праздника"],
            optionsEn: ["5 Major Feasts (Daghavar)", "7 Feasts", "12 Feasts", "3 Feasts"],
            correctAnswerIndex: 0,
            explanationHy: "5 Տաղավար տոներն են՝ Սուրբ Ծնունդ, Սուրբ Զատիկ, Պայծառակերպություն (Վարդավառ), Վերափոխումն Սբ. Աստվածածնի և Խաչվերաց։",
            explanationRu: "5 Великих праздников: Рождество и Богоявление, Пасха (Затик), Преображение (Вардавар), Успение Богородицы и Воздвижение Креста.",
            explanationEn: "The 5 Tabernacle Feasts are: Nativity & Theophany, Easter (Zatik), Transfiguration (Vardavar), Assumption, and Exaltation of the Cross.",
            verseRefHy: "Հայ Եկեղեցու Տոնացույց",
            verseRefRu: "Церковный Календарь Армянской Церкви",
            verseRefEn: "Armenian Church Liturgical Calendar"
        ),

        // =========================================================================
        // MARK: - РАСШИРЕНИЕ 3: ЕВАНГЕЛИЯ (GOSPELS EXPANSION)
        // =========================================================================
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ո՞րն էր Հիսուսի կատարած առաջին հրաշքը ըստ Հովհաննեսի Ավետարանի։",
            questionRu: "Какое первое чудо сотворил Иисус Христос согласно Евангелию от Иоанна?",
            questionEn: "What was Jesus' first miracle according to the Gospel of John?",
            optionsHy: ["Ջուրը գինու փոխելը Կանայի հարսանիքում", "Փոթորիկը հանդարտեցնելը", "5000 մարդու կերակրելը", "Ղազարոսին հարություն տալը"],
            optionsRu: ["Претворение воды в вино на браке в Кане Галилейской", "Укрощение бури", "Насыщение 5000 человек", "Воскрешение Лазаря"],
            optionsEn: ["Turning water into wine at the wedding in Cana", "Calming the storm", "Feeding the 5000", "Raising Lazarus"],
            correctAnswerIndex: 0,
            explanationHy: "Կանայի հարսանիքում Հիսուս ջուրը փոխեց ընտիր գինու՝ Իր մոր՝ Մարիամի խնդրանքով (Հովհ. 2:1-11)։",
            explanationRu: "В Кане Галилейской по просьбе Богородицы Христос совершил первое знамение (Иоанна 2:1-11).",
            explanationEn: "Jesus transformed water into wine at the wedding in Cana of Galilee (John 2:1-11).",
            verseRefHy: "Հովհաննես 2:1-11",
            verseRefRu: "Иоанна 2:1-11",
            verseRefEn: "John 2:1-11"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞ւմ հարություն տվեց Հիսուսը Բեթանիայում՝ նրա մահից չորս օր անց։",
            questionRu: "Кого воскресил Иисус Христос в Вифании на четвертый день после его погребения?",
            questionEn: "Whom did Jesus raise from the dead in Bethany four days after his death?",
            optionsHy: ["Սուրբ Ղազարոսին", "Հայրոսի աղջկան", "Նայինի այրու որդուն", "Նիկոդեմոսին"],
            optionsRu: ["Праведного Лазаря Четверодневного", "Дочь Иаира", "Сына вдовы Наинской", "Никодима"],
            optionsEn: ["Righteous Lazarus Four-Days-Dead", "Jairus' daughter", "Widow of Nain's son", "Nicodemus"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուսն արտասվեց և ձայնեց. «Ղազարո՛ս, դո՛ւրս արի» (Հովհաննես 11:43)։",
            explanationRu: "Иисус воззвал громким голосом: «Лазарь! иди вон», и умерший вышел (Иоанна 11:43).",
            explanationEn: "Jesus called in a loud voice: «Lazarus, come out!» and the dead man emerged (John 11:43).",
            verseRefHy: "Հովհաննես 11:1-44",
            verseRefRu: "Иоанна 11:1-44",
            verseRefEn: "John 11:1-44"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ո՞ր ծառի վրա բարձրացավ կարճահասակ մաքսավոր Զաքեոսը՝ Հիսուսին տեսնելու համար։",
            questionRu: "На какое дерево залез начальник мытарей Закхей в Иерихоне, чтобы увидеть Иисуса?",
            questionEn: "Which tree did Zacchaeus climb in Jericho to see Jesus passing by?",
            optionsHy: ["Ժանտաթզենու (Սիկոմորենու) վրա", "Ձիթենու վրա", "Արմավենու վրա", "Կաղնու վրա"],
            optionsRu: ["На смоковницу (сикомору)", "На маслину", "На пальму", "На дуб"],
            optionsEn: ["A sycamore-fig tree", "An olive tree", "A palm tree", "An oak tree"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուս տեսավ նրան և ասաց. «Զաքեո՛ս, շուտով իջի՛ր, որովհետև այսօր ես պետք է քո տանը մնամ» (Ղուկաս 19:5)։",
            explanationRu: "Иисус сказал ему: «Закхей! сойди скорее, ибо сегодня надобно Мне быть у тебя в доме» (Луки 19:5).",
            explanationEn: "Jesus said: «Zacchaeus, come down immediately. I must stay at your house today» (Luke 19:5).",
            verseRefHy: "Ղուկաս 19:1-10",
            verseRefRu: "Луки 19:1-10",
            verseRefEn: "Luke 19:1-10"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ի՞նչ արեց Հիսուսը Խորհրդավոր Ընթրիքի ժամանակ՝ խոնարհության օրինակ ցույց տալու համար։",
            questionRu: "Что совершил Иисус Христос на Тайной Вечери в знак совершенного смирения и любви?",
            questionEn: "What act of supreme humility and service did Jesus perform at the Last Supper?",
            optionsHy: ["Լվաց աշակերտների ոտքերը", "Օծեց նրանց գլուխները յուղով", "Բաժանեց Իր հագուստները", "Երգեց գոհության սաղմոս"],
            optionsRu: ["Умыл ноги Своим ученикам", "Помазал их головы елеем", "Раздал Свои одежды", "Воспел победный гимн"],
            optionsEn: ["Washed the disciples' feet", "Anointed their heads with oil", "Gave away His garments", "Sang a victory psalm"],
            correctAnswerIndex: 0,
            explanationHy: "«Եթե Ես՝ Տերս և Վարդապետս, լվացի ձեր ոտքերը, դուք էլ պարտավոր եք միմյանց ոտքերը լվանալ» (Հովհ. 13:14)։",
            explanationRu: "«Если Я, Господь и Учитель, умыл ноги вам, то и вы должны умывать ноги друг другу» (Иоанна 13:14).",
            explanationEn: "«Now that I, your Lord and Teacher, have washed your feet, you also should wash one another's feet» (John 13:14).",
            verseRefHy: "Հովհաննես 13:1-17",
            verseRefRu: "Иоанна 13:1-17",
            verseRefEn: "John 13:1-17"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Քանի՞ անգամ Պետրոս առաքյալը ուրացավ Հիսուսին նախքան աքաղաղի կանչելը։",
            questionRu: "Сколько раз апостол Петр отрекся от Христа во дворе первосвященника прежде, чем пропел петух?",
            questionEn: "How many times did Peter deny Jesus before the rooster crowed?",
            optionsHy: ["3 անգամ", "1 անգամ", "7 անգամ", "2 անգամ"],
            optionsRu: ["3 раза", "1 раз", "7 раз", "2 раза"],
            optionsEn: ["3 times", "1 time", "7 times", "2 times"],
            correctAnswerIndex: 0,
            explanationHy: "Աքաղաղը կանչեց, և Պետրոսը հիշեց Տիրոջ խոսքը ու դառնորեն լաց եղավ (Մատթեոս 26:75)։",
            explanationRu: "Вспомнив предсказание Иисуса, Петр вышел вон и горько заплакал (Матфея 26:75).",
            explanationEn: "Then Peter remembered the word Jesus had spoken and he went outside and wept bitterly (Matthew 26:75).",
            verseRefHy: "Մատթեոս 26:69-75",
            verseRefRu: "Матфея 26:69-75",
            verseRefEn: "Matthew 26:69-75"
        ),

        // =========================================================================
        // MARK: - РАСШИРЕНИЕ 4: ВЕТХИЙ ЗАВЕТ (OLD TESTAMENT EXPANSION)
        // =========================================================================
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ի՞նչ տեսավ Հակոբ նահապետը երազում Բեթելում։",
            questionRu: "Что увидел патриарх Иаков в вещем сне в Вефиле?",
            questionEn: "What did Jacob see in his dream at Bethel?",
            optionsHy: ["Սանդուղք, որը հասնում էր երկինք և հրեշտակներ", "Այրվող մորենի", "Յոթ գեր և յոթ նիհար կովեր", "Կարմիր ծովի բացվելը"],
            optionsRu: ["Лестницу до небес, по которой восходили ангелы", "Неопалимую купину", "Семь тучных и семь тощих коров", "Разделившееся море"],
            optionsEn: ["A ladder reaching to heaven with angels ascending and descending", "A burning bush", "Seven fat and seven lean cows", "Parting of the Red Sea"],
            correctAnswerIndex: 0,
            explanationHy: "Հակոբը զարթնեց և ասաց. «Իսկապես Տերը այս տեղում է... սա Աստծո տունն է» (Ծննդոց 28:16-17)։",
            explanationRu: "Иаков воскликнул: «Истинно Господь присутствует на месте сем... это врата небесные!» (Бытие 28:16-17).",
            explanationEn: "Jacob awoke and declared: «Surely the Lord is in this place... this is the gate of heaven» (Genesis 28:16-17).",
            verseRefHy: "Ծննդոց 28:10-19",
            verseRefRu: "Бытие 28:10-19",
            verseRefEn: "Genesis 28:10-19"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ինչպե՞ս Եղիա մարգարեն համբարձվեց երկինք։",
            questionRu: "Каким чудесным образом ветхозаветный пророк Илия был взят на небо живым?",
            questionEn: "How was the Prophet Elijah taken up to heaven alive?",
            optionsHy: ["Հրեղեն կառքով և հրեղեն ձիերով մրրիկի մեջ", "Նավով", "Ամպերի վրա քնելով", "Հրեշտակի թևերով"],
            optionsRu: ["На огненной колеснице с огненными конями в вихре", "На золотом корабле", "Уснув на вершине горы", "На орлиных крыльях"],
            optionsEn: ["In a chariot of fire with horses of fire in a whirlwind", "On a golden boat", "Falling asleep on a mountain", "On eagle wings"],
            correctAnswerIndex: 0,
            explanationHy: "«Հրեղեն մի կառք և հրեղեն ձիեր երևացին, և Եղիան մրրիկով երկինք ելավ» (Դ Թագ. 2:11)։",
            explanationRu: "«Вдруг явилась колесница огненная и кони огненные... и понесся Илия в вихре на небо» (4 Царств 2:11).",
            explanationEn: "«A chariot of fire and horses of fire appeared... and Elijah went up by a whirlwind into heaven» (2 Kings 2:11).",
            verseRefHy: "Դ Թագավորաց 2:11",
            verseRefRu: "4 Царств 2:11",
            verseRefEn: "2 Kings 2:11"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Քանի՞ օր և գիշեր Հովնան մարգարեն մնաց մեծ ձկան փորում։",
            questionRu: "Сколько дней и ночей пророк Иона провел во чреве гигантской рыбы (кита)?",
            questionEn: "How many days and nights did the Prophet Jonah spend in the belly of the huge fish?",
            optionsHy: ["3 օր և 3 գիշեր", "7 օր և 7 գիշեր", "40 օր", "1 օր"],
            optionsRu: ["3 дня и 3 ночи", "7 дней и 7 ночей", "40 дней", "1 день"],
            optionsEn: ["3 days and 3 nights", "7 days and 7 nights", "40 days", "1 day"],
            correctAnswerIndex: 0,
            explanationHy: "Հովնանի 3-օրյա փորձությունը դարձավ Քրիստոսի եռօրյա թաղման և Հարության նախատիպը (Հովնան 2:1, Մատթ. 12:40)։",
            explanationRu: "Пребывание Ионы во чреве кита стало прообразом трехдневного погребения и Воскресения Спасителя (Иона 2:1).",
            explanationEn: "Jonah's three days in the fish foreshadowed Christ's resurrection on the third day (Jonah 1:17, Matthew 12:40).",
            verseRefHy: "Հովնան 2:1",
            verseRefRu: "Иона 2:1",
            verseRefEn: "Jonah 1:17"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ կառուցեց Երուսաղեմի Առաջին Շքեղ Տաճարը։",
            questionRu: "Кто из царей Израиля построил Первый Иерусалимский Храм?",
            questionEn: "Which King of Israel built the First Temple of Jerusalem?",
            optionsHy: ["Սողոմոն Իմաստուն արքան", "Դավիթ թագավորը", "Սավուղ թագավորը", "Եզեկիա թագավորը"],
            optionsRu: ["Царь Соломон Мудрый", "Царь Давид", "Царь Саул", "Царь Езекия"],
            optionsEn: ["King Solomon the Wise", "King David", "King Saul", "King Hezekiah"],
            correctAnswerIndex: 0,
            explanationHy: "Սողոմոն արքան կառուցեց Տիրոջ Տաճարը Լիբանանի մայրիներով և մաքուր ոսկով (Գ Թագ. 6)։",
            explanationRu: "Царь Соломон воздвиг великолепный Храм Господень на горе Мориа (3 Царств 6).",
            explanationEn: "King Solomon constructed the magnificent Temple for the Lord in Jerusalem (1 Kings 6).",
            verseRefHy: "Գ Թագավորաց 6:1-38",
            verseRefRu: "3 Царств 6:1-38",
            verseRefEn: "1 Kings 6:1-38"
        ),

        // =========================================================================
        // MARK: - РАСШИРЕНИЕ: ДОПОЛНИТЕЛЬНЫЕ ВОПРОСЫ (100+ ВОПРОСОВ)
        // =========================================================================
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ էր Պողոս առաքյալի ուղեկիցը, որի անունը նշանակում է «Մխիթարության որդի»։",
            questionRu: "Кто был верным спутником апостола Павла, чье имя означает «Сын утешения»?",
            questionEn: "Who was Paul's companion whose name means «Son of Encouragement»?",
            optionsHy: ["Սուրբ Բառնաբասը", "Սուրբ Սիղան", "Սուրբ Տիտոսը", "Սուրբ Մարկոսը"],
            optionsRu: ["Святой Варнава", "Святой Сила", "Святой Тит", "Святой Марк"],
            optionsEn: ["Saint Barnabas", "Saint Silas", "Saint Titus", "Saint Mark"],
            correctAnswerIndex: 0,
            explanationHy: "Հովսեփը, որ առաքյալների կողմից կոչվեց Բառնաբաս (որ թարգմանվում է Մխիթարության որդի) (Գործք 4:36)։",
            explanationRu: "Иосия, прозванный апостолами Варнавою (что значит — сын утешения) (Деяния 4:36).",
            explanationEn: "Joseph, a Levite from Cyprus, whom the apostles called Barnabas (which means «son of encouragement») (Acts 4:36).",
            verseRefHy: "Գործք 4:36",
            verseRefRu: "Деяния 4:36",
            verseRefEn: "Acts 4:36"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ո՞ւմ մասին էր գրված Պողոս առաքյալի անձնական կարճ նամակը՝ Փիլիմոնին։",
            questionRu: "О чьей судьбе и прощении просил апостол Павел в кратком Послании к Филимону?",
            questionEn: "About whose reconciliation and forgiveness did Paul write in his Epistle to Philemon?",
            optionsHy: ["Փախստական ծառա Օնեսիմոսի", "Տիմոթեոսի", "Ղուկասի", "Ապողոսի"],
            optionsRu: ["О беглом рабе Онисиме, ставшем братом во Христе", "О Тимофее", "О Луке", "Об Аполлосе"],
            optionsEn: ["About Onesimus, the runaway slave who became a brother", "About Timothy", "About Luke", "About Apollos"],
            correctAnswerIndex: 0,
            explanationHy: "Պողոսը խնդրեց Փիլիմոնին ընդունել Օնեսիմոսին ոչ թե որպես ծառա, այլ «սիրելի եղբայր» (Փիլիմոն 1:16)։",
            explanationRu: "Павел просил принять Онисима «не как уже раба, но выше раба, брата возлюбленного» (Филимону 1:16).",
            explanationEn: "Paul urged Philemon to welcome Onesimus «no longer as a slave, but better than a slave, as a dear brother» (Philemon 1:16).",
            verseRefHy: "Փիլիմոն 1:10-18",
            verseRefRu: "Филимону 1:10-18",
            verseRefEn: "Philemon 1:10-18"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ի՞նչ է ասում Պողոս առաքյալը մահացածների հարության մասին Ա Կորնթացիս 15-րդ գլխում։",
            questionRu: "С какими словами обращается апостол Павел к смерти в победной 15-й главе 1 Коринфянам?",
            questionEn: "With what victorious words does Paul address death in 1 Corinthians 15?",
            optionsHy: [
                "«Ո՞ւր է, մա՛հ, քո խայթոցը. ո՞ւր է, դժո՛խք, քո հաղթությունը»",
                "«Մահը հավերժական վերջ է»",
                "«Մենք չենք տեսնի հարություն»",
                "«Մահը անպարտելի է»"
            ],
            optionsRu: [
                "«Смерть! где твое жало? ад! где твоя победа?»",
                "«Смерть есть вечный конец всего»",
                "«Мы не увидим воскресения»",
                "«Смерть непобедима»"
            ],
            optionsEn: [
                "«Where, O death, is your victory? Where, O death, is your sting?»",
                "«Death is the final end»",
                "«We shall not see resurrection»",
                "«Death is unconquerable»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "«Շնորհակալությո՛ւն Աստծուն, որ մեզ հաղթություն է տալիս մեր Տեր Հիսուս Քրիստոսի միջոցով» (Ա Կորնթ. 15:57)։",
            explanationRu: "«Благодарение Богу, даровавшему нам победу чрез Господа нашего Иисуса Христа!» (1 Кор 15:57).",
            explanationEn: "«Thanks be to God! He gives us the victory through our Lord Jesus Christ» (1 Cor 15:57).",
            verseRefHy: "Ա Կորնթացիս 15:55-57",
            verseRefRu: "1 Коринфянам 15:55-57",
            verseRefEn: "1 Corinthians 15:55-57"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ինչպե՞ս է գալու Տիրոջ Օրը՝ ըստ Ա Թեսաղոնիկեցիս 5-րդ գլխի։",
            questionRu: "Как придет день Господень согласно 1-му Посланию к Фессалоникийцам?",
            questionEn: "How will the Day of the Lord come according to 1 Thessalonians 5?",
            optionsHy: ["Ինչպես գողը գիշերով (հանկարծակի)", "Որոտով ու ծանուցմամբ", "Հստակ հայտարարված ժամին", "Ամռան առաջին օրը"],
            optionsRu: ["Как тать (вор) ночью — внезапно", "С громом и предупреждением", "В строго объявленное время", "В первый день лета"],
            optionsEn: ["Like a thief in the night (suddenly)", "With prior thunder and warning", "At an announced time", "On the first day of summer"],
            correctAnswerIndex: 0,
            explanationHy: "«Դուք ինքներդ ստույգ գիտեք, որ Տիրոջ օրը գալիս է այնպես, ինչպես գողը գիշերով» (Ա Թեսաղ. 5:2)։",
            explanationRu: "«Ибо сами вы достоверно знаете, что день Господень так придет, как тать ночью» (1 Фесс 5:2).",
            explanationEn: "«For you know very well that the day of the Lord will come like a thief in the night» (1 Thess 5:2).",
            verseRefHy: "Ա Թեսաղոնիկեցիս 5:2",
            verseRefRu: "1 Фессалоникийцам 5:2",
            verseRefEn: "1 Thessalonians 5:2"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Քանի՞ ընդհանրական (կաթողիկե) թղթեր կան Նոր Կտակարանում։",
            questionRu: "Сколько Соборных посланий (Иакова, Петра, Иоанна, Иуды) входит в состав Нового Завета?",
            questionEn: "How many Catholic (General) Epistles are there in the New Testament?",
            optionsHy: ["7 թուղթ", "14 թուղթ", "4 թուղթ", "12 թուղթ"],
            optionsRu: ["7 посланий", "14 посланий", "4 послания", "12 посланий"],
            optionsEn: ["7 Epistles", "14 Epistles", "4 Epistles", "12 Epistles"],
            correctAnswerIndex: 0,
            explanationHy: "7 Ընդհանրական թղթերն են՝ Հակոբոսի (1), Պետրոսի (2), Հովհաննեսի (3) և Հուդայի (1)։",
            explanationRu: "7 Соборных посланий: Иакова (1), Петра (2), Иоанна (3) и Иуды (1).",
            explanationEn: "The 7 General Epistles include James (1), Peter (2), John (3), and Jude (1).",
            verseRefHy: "Նոր Կտակարանի Կանոն",
            verseRefRu: "Канон Нового Завета",
            verseRefEn: "New Testament Canon"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ի՞նչ խորհուրդ տվեց Պողոս առաքյալը Հռոմեացիներին չարի դեմ պայքարելու համար (Հռոմ. 12:21)։",
            questionRu: "Какое наставление дает апостол Павел в борьбе со злом в Послании к Римлянам (Рим. 12:21)?",
            questionEn: "What instruction does Paul give for overcoming evil in Romans 12:21?",
            optionsHy: [
                "«Մի՛ հաղթվիր չարից, այլ բարիո՛վ հաղթիր չարին»",
                "«Չարին չարով պատասխանիր»",
                "«Հեռացիր աշխարհից»",
                "«Վրեժ լուծիր անհապաղ»"
            ],
            optionsRu: [
                "«Не будь побежден злом, но побеждай зло добром»",
                "«Отвечай злом на зло»",
                "«Убегай от людей»",
                "«Отомсти немедленно»"
            ],
            optionsEn: [
                "«Do not be overcome by evil, but overcome evil with good»",
                "«Repay evil with evil»",
                "«Flee from society»",
                "«Take revenge immediately»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "«Մի՛ հաղթվիր չարից, այլ բարիո՛վ հաղթիր չարին» (Հռոմեացիս 12:21)։",
            explanationRu: "«Не будь побежден злом, но побеждай зло добром» (Рим 12:21).",
            explanationEn: "«Do not be overcome by evil, but overcome evil with good» (Romans 12:21).",
            verseRefHy: "Հռոմեացիս 12:21",
            verseRefRu: "Римлянам 12:21",
            verseRefEn: "Romans 12:21"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ո՞ւմ հարություն տվեց Պետրոս առաքյալը Հոպպե քաղաքում (Գործք 9)։",
            questionRu: "Кого воскресил апостол Петр в Иоппии по горячим молитвам верующих?",
            questionEn: "Whom did Apostle Peter raise from the dead in Joppa through fervent prayer?",
            optionsHy: ["Բարեգործ Տաբիթային (Դորկասին)", "Մարիամին", "Սապֆիրային", "Եվնիկեին"],
            optionsRu: ["Благочестивую Тавифу (Серну)", "Марию", "Сапфиру", "Евнику"],
            optionsEn: ["Devout Tabitha (Dorcas)", "Mary", "Sapphira", "Eunice"],
            correctAnswerIndex: 0,
            explanationHy: "Տաբիթան լի էր բարի գործերով և ողորմությամբ. Պետրոսը աղոթեց և ասաց. «Տաբիթա՛, վե՛ր կաց» (Գործք 9:40)։",
            explanationRu: "Тавифа была полна добрых дел; Петр помолился, и она открыла глаза (Деяния 9:40).",
            explanationEn: "Tabitha was known for helping the poor; Peter prayed, saying: «Tabitha, get up!» (Acts 9:40).",
            verseRefHy: "Գործք 9:36-42",
            verseRefRu: "Деяния 9:36-42",
            verseRefEn: "Acts 9:36-42"
        ),

        // --- ДОПОЛНЕНИЕ АРМЯНСКОЙ ЦЕРКВИ ---
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞ր գետում Սուրբ Գրիգոր Լուսավորիչը մկրտեց Տրդատ արքային և հայ ժողովրդին։",
            questionRu: "В водах какой реки святой Григорий Просветитель крестил царя Трдата III, войско и армянский народ?",
            questionEn: "In the waters of which river did Saint Gregory the Illuminator baptize King Trdat III and the Armenian nation?",
            optionsHy: ["Արածանի (Եփրատի վտակ) գետում", "Արաքս գետում", "Հրազդան գետում", "Սևանա լճում"],
            optionsRu: ["В реке Арацани (Восточный Евфрат)", "В реке Аракс", "В реке Раздан", "В озере Севан"],
            optionsEn: ["In the Aratsani River (Eastern Euphrates)", "In the Aras River", "In the Hrazdan River", "In Lake Sevan"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Գրիգորը Արածանիի ջրերում մկրտեց արքայական ընտանիքին և հարյուր հազարավոր հայերի։",
            explanationRu: "В священных водах Арацани святитель крестил царя, царицу Ашхен, сестру Хосровадухт и народ.",
            explanationEn: "In the waters of the Aratsani River, Saint Gregory baptized the Royal Family and the army.",
            verseRefHy: "Ագաթանգեղոս (IV դար)",
            verseRefRu: "Агафангел (IV век)",
            verseRefEn: "Agathangelos (4th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ո՞վ էր V դարի հայ առաջին կին սուրբ նահատակը, որը նախընտրեց հավատքը հանուն Քրիստոսի։",
            questionRu: "Какая святая армянская княгиня V века приняла мученический венец, отказавшись предать веру Христову?",
            questionEn: "Which 5th-century Armenian princess and saint chose martyrdom over renouncing her Christian faith?",
            optionsHy: ["Սուրբ Շուշանիկը", "Սուրբ Սանդուխտը", "Սուրբ Աշխենը", "Սուրբ Խոսրովիդուխտը"],
            optionsRu: ["Святая Шушаник (Вардени)", "Святая Сандухт", "Святая Ашхен", "Святая Хосровадухт"],
            optionsEn: ["Saint Shushanik (Vardeni)", "Saint Sandukht", "Saint Ashkhen", "Saint Khosrovidukht"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Շուշանիկը՝ Վարդան Մամիկոնյանի դուստրը, համբերատարությամբ կրեց չարչարանքները հանուն Քրիստոսի։",
            explanationRu: "Святая Шушаник, дочь Вардана Мамиконяна, явила образец несокрушимой стойкости веры.",
            explanationEn: "Saint Shushanik, daughter of Vardan Mamikonian, endured torture for her faith in Christ.",
            verseRefHy: "«Շուշանիկի Վկայաբանություն» (V դար)",
            verseRefRu: "«Мученичество Шушаник» (V век)",
            verseRefEn: "Martyrdom of Saint Shushanik (5th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞վ էր Հայ Եկեղեցու մեծ Իմաստասեր (Փիլիսոփա) Կաթողիկոսը (VIII դար)։",
            questionRu: "Какой католикос VIII века прозван «Философом» (Имастасер) и составил знаменитую «Книгу канонов» (Կանոնագիրք) Армянской Церкви?",
            questionEn: "Which 8th-century Catholicos was titled «The Philosopher» and compiled the «Book of Canons» of the Armenian Church?",
            optionsHy: ["Սուրբ Հովհան Օձնեցին", "Սուրբ Ներսես Շնորհալին", "Սուրբ Գրիգոր Լուսավորիչը", "Սուրբ Կոմիտասը"],
            optionsRu: ["Святой Ован Одзнеци", "Святой Нерсес Шнорали", "Святой Григорий Просветитель", "Святой Комитас Ахцеци"],
            optionsEn: ["Saint John of Otzun (Hovhan Odznetsi)", "Saint Nerses Shnorhali", "Saint Gregory the Illuminator", "Saint Komitas Akhtsetsi"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Հովհան Օձնեցի Հայրապետը համակարգեց Հայոց Կանոնագիրքը և գրեց հոգևոր շարականներ։",
            explanationRu: "Святой Иоанн Одзнеци составил Армянский Судебник-Канонагирк и созвал Двинский и Манцикертский соборы.",
            explanationEn: "Saint John of Otzun systematized the Armenian Book of Canons and composed deep spiritual hymns.",
            verseRefHy: "Հայոց Կանոնագիրք (VIII դար)",
            verseRefRu: "Армянский Канонагирк (VIII век)",
            verseRefEn: "Armenian Book of Canons (8th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ի՞նչ հոգևոր երգեր են «Շարականները» Հայ Առաքելական Եկեղեցում։",
            questionRu: "Что представляют собой священные «Шараканы» (Շարական) в богослужении Армянской Церкви?",
            questionEn: "What are «Sharakans» (Շարական) in the liturgical tradition of the Armenian Church?",
            optionsHy: ["Հոգևոր օրհներգեր և աղոթք-երգեր", "Եկեղեցական օրենքներ", "Պատմական տարեգրություններ", "Ճարտարապետական նախագծեր"],
            optionsRu: ["Канонические духовные песнопения и гимны", "Своды законов", "Летописные хроники", "Архитектурные чертежи"],
            optionsEn: ["Canonical spiritual hymns and canticles", "Legal codes", "Historical chronicles", "Architectural plans"],
            correctAnswerIndex: 0,
            explanationHy: "Շարականները (շարքով կանոնական երգեր) ստեղծվել են Մեսրոպ Մաշտոցի, Սահակ Պարթևի և Ներսես Շնորհալու կողմից։",
            explanationRu: "Шараканы — древние гимны, собранные в книге «Шаракноц», наполненные глубокой поэзией веры.",
            explanationEn: "Sharakans are ancient liturgical hymns composed by Armenian Church fathers and collected in the Sharaknots.",
            verseRefHy: "Շարակնոց (Հայ Եկեղեցու Երգարան)",
            verseRefRu: "Шаракноц (Книга Гимнов)",
            verseRefEn: "Sharaknots (Armenian Hymnal)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞ր հայոց արքայադուստրը դարձավ առաջին քրիստոնյա նահատակը 1-ին դարում՝ Թադեոս առաքյալի քարոզով։",
            questionRu: "Какая святая царевна стала первой мученицей в Армении в I веке, уверовав от проповеди апостола Фаддея?",
            questionEn: "Which royal princess became the first female martyr of Armenia in the 1st century through Apostle Thaddeus?",
            optionsHy: ["Սուրբ Սանդուխտ Կույսը", "Սուրբ Հռիփսիմեն", "Սուրբ Գայանեն", "Սուրբ Աշխենը"],
            optionsRu: ["Святая дева Сандухт (царевна)", "Святая Рипсиме", "Святая Гаяне", "Святая Ашхен"],
            optionsEn: ["Saint Sandukht the Virgin", "Saint Hripsime", "Saint Gayane", "Saint Ashkhen"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Սանդուխտը՝ Սանատրուկ թագավորի դուստրը, չուրացավ Քրիստոսին և նահատակվեց հավատքի համար։",
            explanationRu: "Святая Сандухт, дочь царя Санатрука, предпочла венец мученичества за Христа царским почестям.",
            explanationEn: "Saint Sandukht, daughter of King Sanatruk, embraced martyrdom for Christ in the 1st century.",
            verseRefHy: "Հայոց Վարք Սրբոց (I դար)",
            verseRefRu: "Жития Святых (I век)",
            verseRefEn: "Armenian Synaxarion (1st Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ո՞ր տոնն է նվիրված Քրիստոսի Պայծառակերպությանը Հայ Եկեղեցում (ժողովրդական՝ Վարդավառ)։",
            questionRu: "Какой праздник Господень в Армянской Церкви посвящен Преображению Христа на горе Фавор (в народе Вардавар)?",
            questionEn: "Which Major Feast of the Armenian Church commemorates the Transfiguration of Jesus on Mount Tabor (Vardavar)?",
            optionsHy: ["Պայծառակերպություն Տեառն (Վարդավառ)", "Խաչվերաց", "Տյառնընդառաջ", "Համբարձում"],
            optionsRu: ["Преображение Господне (Вардавар)", "Воздвижение Креста", "Сретение (Тьярнэндарадж)", "Вознесение"],
            optionsEn: ["Feast of the Transfiguration (Vardavar)", "Exaltation of the Cross", "Presentation (Trndez)", "Ascension"],
            correctAnswerIndex: 0,
            explanationHy: "Պայծառակերպության տոնին Հիսուս Իր աստվածային փառքով պայծառացավ Թաբոր լեռան վրա (Մատթ. 17)։",
            explanationRu: "В праздник Преображения вспоминается явление Славы Божьей ученикам на горе Фавор (Матфея 17).",
            explanationEn: "The Transfiguration celebrates Christ revealing His divine glory to the apostles on Mount Tabor.",
            verseRefHy: "Մատթեոս 17:1-8",
            verseRefRu: "Матфея 17:1-8",
            verseRefEn: "Matthew 17:1-8"
        ),

        // --- ДОПОЛНЕНИЕ ЕВАНГЕЛИЙ И ВЕТХОГО ЗАВЕТА ---
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ի՞նչ պատվիրեց Հիսուսը Երանիների մեջ՝ Լեռան Քարոզում (Մատթ. 5:3)։",
            questionRu: "Какое первое блаженство возвестил Спаситель в Нагорной проповеди (Матфея 5:3)?",
            questionEn: "What is the first Beatitude given by Jesus in the Sermon on the Mount (Matthew 5:3)?",
            optionsHy: [
                "«Երանի՜ հոգով աղքատներին, որովհետև նրանցն է երկնքի արքայությունը»",
                "«Երանի հարուստներին»",
                "«Երանի հզորներին»",
                "«Երանի հաղթողներին»"
            ],
            optionsRu: [
                "«Блаженны нищие духом, ибо их есть Царство Небесное»",
                "«Блаженны богатые»",
                "«Блаженны властвующие»",
                "«Блаженны победители»"
            ],
            optionsEn: [
                "«Blessed are the poor in spirit, for theirs is the kingdom of heaven»",
                "«Blessed are the rich»",
                "«Blessed are the mighty»",
                "«Blessed are the victors»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "Հոգով աղքատ լինել նշանակում է լինել խոնարհ և ամեն բանում ապավինել Աստծո ողորմությանը։",
            explanationRu: "Нищета духа означает смирение, осознание своей зависимости от благодати Божьей.",
            explanationEn: "Poor in spirit refers to humble spiritual reliance on God's boundless grace.",
            verseRefHy: "Մատթեոս 5:3",
            verseRefRu: "Матфея 5:3",
            verseRefEn: "Matthew 5:3"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ի՞նչ հրաշք գործեց Հիսուսը Գենեսարեթի (Գալիլեայի) ծովի վրա փոթորկի ժամանակ։",
            questionRu: "Какое чудо совершил Иисус на Галилейском озере, когда лодка с учениками погибала от бури?",
            questionEn: "What miracle did Jesus perform on the Sea of Galilee during a violent storm?",
            optionsHy: ["Սաստեց քամուն և ալիքներին, և մեծ խաղաղություն տիրեց", "Լողալով ափ հասավ", "Նոր նավ ստեղծեց", "Կանչեց ձկներին"],
            optionsRu: ["Запретил ветру и волнам, и настала великая тишина", "Доплыл до берега вплавь", "Сотворил новый корабль", "Подозвал рыб"],
            optionsEn: ["Rebuked the wind and waves, and it was completely calm", "Swam to the shore", "Created a new boat", "Called the fish"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուսն ասաց. «Լռի՛ր, դադարի՛ր», և քամին դադարեց (Մարկոս 4:39)։",
            explanationRu: "Иисус сказал морю: «Умолкни, перестань!», и сделалась великая тишина (Марка 4:39).",
            explanationEn: "Jesus said to the waves: «Quiet! Be still!», and the wind died down (Mark 4:39).",
            verseRefHy: "Մարկոս 4:35-41",
            verseRefRu: "Марка 4:35-41",
            verseRefEn: "Mark 4:35-41"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ առաջնորդեց Իսրայելի ժողովրդին Եգիպտոսի ստրկությունից դեպի Կարմիր ծով։",
            questionRu: "Кто по повелению Божьему вывел израильский народ из египетского рабства через Красное море?",
            questionEn: "Who led the people of Israel out of Egyptian slavery through the parted Red Sea?",
            optionsHy: ["Սուրբ Մովսես մարգարեն", "Ահարոն քահանան", "Հեսու Նավեն", "Գեդեոնը"],
            optionsRu: ["Пророк Моисей Боговидец", "Аарон первосвященник", "Иисус Навин", "Гедеон"],
            optionsEn: ["Prophet Moses", "Aaron the Priest", "Joshua son of Nun", "Gideon"],
            correctAnswerIndex: 0,
            explanationHy: "Մովսեսը մեկնեց գավազանը, և Տերը բաժանեց Կարմիր ծովի ջրերը (Ելից 14)։",
            explanationRu: "Моисей простер руку свою на море, и расступились воды (Исход 14).",
            explanationEn: "Moses stretched out his hand over the sea, and the Lord divided the waters (Exodus 14).",
            verseRefHy: "Ելից 14:21-31",
            verseRefRu: "Исход 14:21-31",
            verseRefEn: "Exodus 14:21-31"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Քանի՞ պատվիրաններ տվեց Աստված Մովսեսին Սինա լեռան վրա (Տասնաբանյա)։",
            questionRu: "Сколько священных заповедей (Декалог) начертал Господь на каменных скрижалях на горе Синай?",
            questionEn: "How many Commandments (the Decalogue) did God give Moses on Mount Sinai?",
            optionsHy: ["10 Պատվիրան", "12 պատվիրան", "7 պատվիրան", "40 պատվիրան"],
            optionsRu: ["10 Заповедей (Декалог)", "12 заповедей", "7 заповедей", "40 заповедей"],
            optionsEn: ["10 Commandments (Decalogue)", "12 commandments", "7 commandments", "40 commandments"],
            correctAnswerIndex: 0,
            explanationHy: "Տասը Պատվիրանները տրվեցին քարե տախտակների վրա Սինա լեռան վրա (Ելից 20)։",
            explanationRu: "Десять Заповедей стали священным нравственным законом Завета (Исход 20).",
            explanationEn: "The Ten Commandments were inscribed on stone tablets at Mount Sinai (Exodus 20).",
            verseRefHy: "Ելից 20:1-17",
            verseRefRu: "Исход 20:1-17",
            verseRefEn: "Exodus 20:1-17"
        )
    ]
}
