import Foundation

extension QuizDatabase {
    // // MARK: - 4. АРМЯНСКАЯ ЦЕРКОВЬ И СВЯТЫЕ (CHURCH HISTORY)
    static let questionsChurch: [QuizQuestion] = [
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞ր երկու առաքյալներն են համարվում Հայաստանյայց Առաքելական Եկեղեցու Առաջին Լուսավորիչները։",
            questionRu: "Какие два святых апостола из 12 считаются Первопросветителями Армении?",
            questionEn: "Which two apostles of the 12 are recognized as the First Illuminators of Armenia?",
            optionsHy: ["Սուրբ Թադեոս և Սուրբ Բարդուղիմեոս", "Սուրբ Պետրոս և Սուրբ Պողոս", "Սուրբ Հովհաննես և Սուրբ Անդրեաս", "Սուրբ Մատթեոս և Սուրբ Ղուկաս"],
            optionsRu: ["Святой Фаддей и Святой Варфоломей", "Святой Петр и Святой Павел", "Святой Иоанн и Святой Андрей", "Святой Матфей и Святой Лука"],
            optionsEn: ["Saint Thaddeus and Saint Bartholomew", "Saint Peter and Saint Paul", "Saint John and Saint Andrew", "Saint Matthew and Saint Luke"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Թադեոս և Սուրբ Բարդուղիմեոս առաքյալները 1-ին դարում բերեցին Քրիստոնեությունը Հայաստան։",
            explanationRu: "Апостолы Фаддей и Варфоломей принесли свет Евангелия в Армению в I веке.",
            explanationEn: "Apostles Thaddeus and Bartholomew preached the Gospel and were martyred in Armenia in the 1st century.",
            verseRefHy: "Հայոց Եկեղեցու Պատմություն (1-ին դար)",
            verseRefRu: "История Армянской Церкви (I век)",
            verseRefEn: "History of the Armenian Church (1st Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞ր թվականին Հայաստանը ընդունեց Քրիստոնեությունը որպես պետական կրոն (առաջինը աշխարհում)։",
            questionRu: "В каком году Армения первой в мире провозгласила христианство государственной религией?",
            questionEn: "In which year did Armenia adopt Christianity as its state religion (first in the world)?",
            optionsHy: ["301 թ.", "313 թ.", "325 թ.", "451 թ."],
            optionsRu: ["301 г.", "313 г.", "325 г.", "451 г."],
            optionsEn: ["301 AD", "313 AD", "325 AD", "451 AD"],
            correctAnswerIndex: 0,
            explanationHy: "301 թվականին Սուրբ Գրիգոր Լուսավորչի և Տրդատ Գ Մեծ արքայի շնորհիվ Հայաստանը դարձավ առաջին քրիստոնյա պետությունը։",
            explanationRu: "В 301 году при святом Григории Просветителе и царе Трдате III Армения стала первым христианским государством.",
            explanationEn: "In 301 AD, under Saint Gregory the Illuminator and King Tiridates III, Armenia became the first Christian nation.",
            verseRefHy: "Հայոց Պատմություն 301 թ.",
            verseRefRu: "История Армении 301 г.",
            verseRefEn: "History of Armenia 301 AD"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Քանի՞ տարի անցկացրեց Սուրբ Գրիգոր Լուսավորիչը Խոր Վիրապի խոր փոսում։",
            questionRu: "Сколько лет святой Григорий Просветитель провел в заточении в темнице Хор Вирап?",
            questionEn: "How many years was Saint Gregory the Illuminator imprisoned in the pit of Khor Virap?",
            optionsHy: ["7 տարի", "10 տարի", "13-14 տարի", "40 տարի"],
            optionsRu: ["7 лет", "10 лет", "13-14 лет", "40 лет"],
            optionsEn: ["7 years", "10 years", "13-14 years", "40 years"],
            correctAnswerIndex: 2,
            explanationHy: "Սուրբ Գրիգորը մոտ 14 տարի հրաշքով ապրեց Խոր Վիրապի խորխորատում՝ հավատարիմ մնալով Քրիստոսին։",
            explanationRu: "Святой Григорий провел около 14 лет в темнице Хор Вирап, поддерживаемый молитвой и помощью благочестивой женщины.",
            explanationEn: "Saint Gregory miraculously survived approximately 14 years in the deep dungeon pit of Khor Virap.",
            verseRefHy: "Ագաթանգեղոս, Պատմություն Հայոց",
            verseRefRu: "Агафангел, «История Армении»",
            verseRefEn: "Agathangelos, History of the Armenians"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .easy,
            questionHy: "Ո՞վ ստեղծեց Հայոց Այբուբենը 405 թվականին Աստվածաշունչը թարգմանելու համար։",
            questionRu: "Кто создал армянский алфавит в 405 году для перевода Священного Писания?",
            questionEn: "Who created the Armenian alphabet in 405 AD to translate the Holy Bible?",
            optionsHy: ["Սուրբ Մեսրոպ Մաշտոցը", "Սուրբ Գրիգոր Նարեկացին", "Մովսես Խորենացին", "Սուրբ Սահակ Պարթևը"],
            optionsRu: ["Святой Месроп Маштоц", "Святой Григор Нарекаци", "Мовсес Хоренаци", "Святой Саак Партев"],
            optionsEn: ["Saint Mesrop Mashtots", "Saint Gregory of Narek", "Movses Khorenatsi", "Saint Sahak Partev"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Մեսրոպ Մաշտոցը Աստծո ներշնչանքով ստեղծեց 36 հայերեն տառերը 405 թվականին։",
            explanationRu: "Святой Месроп Маштоц при поддержке католикоса Саака и царя Врамшапуха создал армянские письмена.",
            explanationEn: "Saint Mesrop Mashtots, inspired by God, invented the Armenian alphabet in 405 AD.",
            verseRefHy: "Կորյուն, «Վարք Մաշտոցի»",
            verseRefRu: "Корюн, «Житие Маштоца»",
            verseRefEn: "Koryun, The Life of Mashtots"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ո՞րն էր հայերեն թարգմանված առաջին նախադասությունը Աստվածաշնչից։",
            questionRu: "Какое первое предложение было переведено на армянский язык из Библии?",
            questionEn: "What was the very first sentence translated into Armenian from the Bible?",
            optionsHy: [
                "«Ճանաչել զիմաստութիւն եւ զխրատ, իմանալ զբանս հանճարոյ»",
                "«Ի սկզբանէ էր Բանն, եւ Բանն էր առ Աստուած»",
                "«Սկզբում Աստված ստեղծեց երկինքն ու երկիրը»",
                "«Տէրն իմ հովիւն է, եւ ինձ ոչինչ չի պակասիլ»"
            ],
            optionsRu: [
                "«Познать мудрость и наставление, понять изречения разума»",
                "«В начале было Слово, и Слово было у Бога»",
                "«В начале сотворил Бог небо и землю»",
                "«Господь — Пастырь мой; я ни в чем не буду нуждаться»"
            ],
            optionsEn: [
                "«To know wisdom and instruction; to perceive the words of understanding»",
                "«In the beginning was the Word, and the Word was with God»",
                "«In the beginning God created the heavens and the earth»",
                "«The Lord is my shepherd; I shall not want»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "Սողոմոնի Առակաց գրքի առաջին տողն էր՝ «Ճանաչել զիմաստութիւն եւ զխրատ...»։",
            explanationRu: "Священное Писание на армянском началось со стиха Притчей Соломона 1:2.",
            explanationEn: "The Armenian translation of the Scriptures opened with Proverbs 1:2.",
            verseRefHy: "Առակաց 1:2",
            verseRefRu: "Притчи 1:2",
            verseRefEn: "Proverbs 1:2"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ինչպե՞ս է կոչվում Աստվածաշնչի հայերեն թարգմանությունը համաշխարհային մշակույթում։",
            questionRu: "Как в мировом христианском богословии называют армянский перевод Библии V века?",
            questionEn: "How is the 5th-century Armenian translation of the Bible revered in world scholarship?",
            optionsHy: ["«Թարգմանությունների Թագուհի»", "«Արծաթե Գիրք»", "«Ոսկեդարյան Մատյան»", "«Արևելյան Ավետարան»"],
            optionsRu: ["«Царица переводов» (Queen of Translations)", "«Серебряная Книга»", "«Летопись Золотого века»", "«Восточное Евангелие»"],
            optionsEn: ["«Queen of Translations»", "«Silver Codex»", "«Golden Age Tome»", "«Gospel of the Orient»"],
            correctAnswerIndex: 0,
            explanationHy: "Իր անկրկնելի ճշգրտության և գեղեցկության շնորհիվ հայերեն Աստվածաշունչը կոչվում է «Թարգմանությունների Թագուհի»։",
            explanationRu: "За непревзойденную точность, поэтичность и чистоту армянский перевод назван «Царицей переводов».",
            explanationEn: "Due to its unmatched accuracy and literary beauty, the Armenian Bible is called the «Queen of Translations».",
            verseRefHy: "Ոսկեդար (V դար)",
            verseRefRu: "Золотой Век Армении (V век)",
            verseRefEn: "Golden Age of Armenia (5th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ո՞վ է հեղինակել հանճարեղ «Մատյան Ողբերգության» (Նարեկ) աղոթագրքի գլուխգործոցը։",
            questionRu: "Кто является автором великой молитвенной книги «Книга скорбных песнопений» (Нарек)?",
            questionEn: "Who authored the spiritual masterpiece «Book of Lamentations» (Narek)?",
            optionsHy: ["Սուրբ Գրիգոր Նարեկացին", "Սուրբ Ներսես Շնորհալին", "Եղիշեն", "Գրիգոր Տաթևացին"],
            optionsRu: ["Святой Григор Нарекаци", "Святой Нерсес Шнорали", "Егише", "Григор Татеваци"],
            optionsEn: ["Saint Gregory of Narek", "Saint Nerses the Gracious", "Yeghishe", "Gregory of Tatev"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Գրիգոր Նարեկացին 10-րդ դարում գրեց «Մատյան Ողբերգության» աղոթագիրքը («Ի խորոց սրտի»)։",
            explanationRu: "Святой монах Григор Нарекаци в X веке создал бессмертную «Книгу скорбных песнопений» («Из глубин сердца»).",
            explanationEn: "Saint Gregory of Narek composed the «Book of Lamentations» in the 10th century at Narekavank.",
            verseRefHy: "Մատյան Ողբերգության (X դար)",
            verseRefRu: "Книга скорбных песнопений (X век)",
            verseRefEn: "Book of Lamentations (10th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ո՞վ գրեց հայտնի 24-ժամյա աղոթքը՝ «Հավատով Խոստովանիմ»։",
            questionRu: "Кто написал знаменитую молитву на каждый час дня «С верою исповедую» (Հաւատով խոստովանիմ)?",
            questionEn: "Who composed the beloved 24-hour prayer «With Faith I Confess» (Havadov Khosdovanim)?",
            optionsHy: ["Սուրբ Ներսես Շնորհալի Կաթողիկոսը", "Սուրբ Գրիգոր Լուսավորիչը", "Սուրբ Մեսրոպ Մաշտոցը", "Սուրբ Հովհան Օձնեցին"],
            optionsRu: ["Святой Нерсес Шнорали (Благодатный)", "Святой Григорий Просветитель", "Святой Месроп Маштоц", "Святой Ован Одзнеци"],
            optionsEn: ["Saint Nerses the Gracious (Shnorhali)", "Saint Gregory the Illuminator", "Saint Mesrop Mashtots", "Saint John of Otzun"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Ներսես Շնորհալի Հայրապետը (12-րդ դար) գրեց «Հավատով Խոստովանիմ» 24 տներից բաղկացած աղոթքը։",
            explanationRu: "Святой католикос Нерсес Шнорали (XII век) сложил 24 вдохновенные строфы молитвы «С верою исповедую».",
            explanationEn: "Catholicos Saint Nerses Shnorhali composed the 24-stanza prayer «With Faith I Confess» in the 12th century.",
            verseRefHy: "Հավատով Խոստովանիմ (XII դար)",
            verseRefRu: "«С верою исповедую» (XII век)",
            verseRefEn: "With Faith I Confess (12th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .medium,
            questionHy: "Ի՞նչ նշանաբանով առաջնորդվեց Սուրբ Վարդան Մամիկոնյանը Ավարայրի ճակատամարտում (451 թ.)։",
            questionRu: "С каким бессмертным заветом вел воинов святой Вардан Мамиконян на Аварайрском поле (451 г.)?",
            questionEn: "With what motto did Saint Vardan Mamikonian lead the defenders at Avarayr (451 AD)?",
            optionsHy: [
                "«Մահ ոչ իմացեալ՝ մահ է, մահ իմացեալ՝ անմահութիւն»",
                "«Հաղթանակ կամ մահ»",
                "«Խաղաղություն ամենեցուն»",
                "«Ազատություն և պատիվ»"
            ],
            optionsRu: [
                "«Смерть неосознанная есть смерть, смерть осознанная — бессмертие»",
                "«Победа или смерть»",
                "«Мир всем народам»",
                "«Свобода и честь»"
            ],
            optionsEn: [
                "«Unconscious death is death, conscious death is immortality»",
                "«Victory or death»",
                "«Peace to all nations»",
                "«Freedom and honor»"
            ],
            correctAnswerIndex: 0,
            explanationHy: "Վարդանանց քաջերը պաշտպանեցին քրիստոնեական հավատը՝ «Վասն Յիսուսի, վասն հայրենեաց»։",
            explanationRu: "Святые Вардананц пали за веру Христову и свободу совести под девизом осознанного бессмертия.",
            explanationEn: "Saint Vardan and his companions defended the Christian faith at Avarayr with the immortal words on conscious sacrifice.",
            verseRefHy: "Եղիշե, «Վարդանի և Հայոց պատերազմի մասին»",
            verseRefRu: "Егише, «О Вардане и войне армянской»",
            verseRefEn: "Yeghishe, The History of Vardan and the Armenian War"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞ր սուրբ կույսերի նահատակության վայրերում կառուցվեցին Վաղարշապատի հոյակապ տաճարները։",
            questionRu: "В честь каких святых дев-мучениц воздвигнуты великие храмы Эчмиадзина?",
            questionEn: "In honor of which holy virgin-martyrs were the great temples of Vagharshapat built?",
            optionsHy: ["Սուրբ Հռիփսիմե և Սուրբ Գայանե", "Սուրբ Շուշանիկ և Սուրբ Սանդուխտ", "Սուրբ Աննա և Սուրբ Եղիսաբեթ", "Սուրբ Մարիամ և Սուրբ Մարթա"],
            optionsRu: ["Святая Рипсиме и Святая Гаяне", "Святая Шушаник и Святая Сандухт", "Святая Анна и Святая Елисавета", "Святая Мария и Святая Марфа"],
            optionsEn: ["Saint Hripsime and Saint Gayane", "Saint Shushanik and Saint Sandukht", "Saint Anna and Saint Elizabeth", "Saint Mary and Saint Martha"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Հռիփսիմյանց կույսերի նահատակության վայրերում Սուրբ Գրիգոր Լուսավորիչը հիմնեց վկայարանները։",
            explanationRu: "На местах мученического подвига святых дев Рипсиме, Гаяне и Мариамне были воздвигнуты святые храмы.",
            explanationEn: "Saint Gregory the Illuminator established chapels on the martyrdom sites of Saint Hripsime and Saint Gayane.",
            verseRefHy: "Ագաթանգեղոս (IV դար)",
            verseRefRu: "Агафангел (IV век)",
            verseRefEn: "Agathangelos (4th Century)"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ի՞նչ է նշանակում «Էջմիածին» բառը։",
            questionRu: "Что означает священное название первопрестольного собора «Эчмиадзин» (Էջմիածին)?",
            questionEn: "What does the sacred name of the Holy See «Echmiadzin» (Էջմիածին) mean?",
            optionsHy: ["«Իջավ Միածինը» (Միածին Որդին)", "«Սուրբ Լույս»", "«Աստծո Տուն»", "«Հավերժական Խաչ»"],
            optionsRu: ["«Сошел Единородный» (Сын Божий)", "«Святой Свет»", "«Дом Божий»", "«Вечный Крест»"],
            optionsEn: ["«The Only Begotten Descended»", "«Holy Light»", "«House of God»", "«Eternal Cross»"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Գրիգոր Լուսավորչի տեսիլքում Հիսուս Քրիստոս իջավ ոսկե մուրճով և ցույց տվեց Մայր Տաճարի տեղը։",
            explanationRu: "В видении святого Григория Сам Единородный Сын Божий сошел с небес и золотым молотом указал место храма.",
            explanationEn: "In Saint Gregory's vision, Christ the Only Begotten descended with a golden hammer to strike the location of the Cathedral.",
            verseRefHy: "Մայր Աթոռ Սուրբ Էջմիածին",
            verseRefRu: "Первопрестольный Святой Эчмиадзин",
            verseRefEn: "Mother See of Holy Etchmiadzin"
        ),
        QuizQuestion(
            category: .churchHistory,
            difficulty: .hard,
            questionHy: "Ո՞ր սրբությունն է պահվում Էջմիածնի գանձատանը, որով խոցել էին Քրիստոսի կողը Խաչի վրա։",
            questionRu: "Какая великая святыня хранится в Эчмиадзине, которой сотник пронзил ребро Христа на Кресте?",
            questionEn: "Which holy relic is preserved in Echmiadzin, with which Christ's side was pierced on the Cross?",
            optionsHy: ["Սուրբ Գեղարդը (Հռոմեացի զինվորի նիզակը)", "Փշե Պսակը", "Սուրբ Պատանքը", "Սուրբ Գավաթը"],
            optionsRu: ["Святой Гегард (Копье Лонгина)", "Терновый венец", "Плащаница", "Святой Грааль"],
            optionsEn: ["Holy Lance (Spear of Longinus / Geghard)", "Crown of Thorns", "Holy Shroud", "Holy Grail"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Թադեոս առաքյալը Սուրբ Գեղարդը բերեց Հայաստան, որը դարեր շարունակ պահվել է Գեղարդավանքում, ապա Էջմիածնում։",
            explanationRu: "Апостол Фаддей принес Святое Копье в Армению, давшее имя монастырю Гегардаванк.",
            explanationEn: "Apostle Thaddeus brought the Holy Lance to Armenia, where it is venerated at Holy Etchmiadzin.",
            verseRefHy: "Սուրբ Էջմիածնի Գանձեր",
            verseRefRu: "Сокровищница Святого Эчмиадзина",
            verseRefEn: "Treasury of Holy Etchmiadzin"
        ),
    ]  // конец массива
}
