import Foundation

extension QuizDatabase {
    // // MARK: - 1. ВЕТХИЙ ЗАВЕТ (OLD TESTAMENT)
    static let questionsOT: [QuizQuestion] = [
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Քանի՞ օրում Աստված արարեց աշխարհը և հանգստացավ յոթերորդ օրը։",
            questionRu: "За сколько дней Бог сотворил мир, после чего почил в день седьмой?",
            questionEn: "In how many days did God create the world before resting on the seventh day?",
            optionsHy: ["5 օրում", "6 օրում", "7 օրում", "40 օրում"],
            optionsRu: ["За 5 дней", "За 6 дней", "За 7 дней", "За 40 дней"],
            optionsEn: ["In 5 days", "In 6 days", "In 7 days", "In 40 days"],
            correctAnswerIndex: 1,
            explanationHy: "Աստված արարեց երկինքն ու երկիրը 6 օրում, իսկ յոթերորդ օրը հանգստացավ Իր բոլոր գործերից։",
            explanationRu: "Бог сотворил небо и землю за 6 дней, а в седьмой день почил от всех дел Своих.",
            explanationEn: "God created the heavens and the earth in 6 days, and rested on the seventh day from all His work.",
            verseRefHy: "Ծննդոց 2:2",
            verseRefRu: "Бытие 2:2",
            verseRefEn: "Genesis 2:2"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ տապան կառուցեց ջրհեղեղից փրկվելու համար։",
            questionRu: "Кто построил ковчег для спасения от Великого потопа?",
            questionEn: "Who built the ark to survive the Great Flood?",
            optionsHy: ["Աբրահամը", "Մովսեսը", "Նոյը", "Դավիթը"],
            optionsRu: ["Авраам", "Моисей", "Ной", "Давид"],
            optionsEn: ["Abraham", "Moses", "Noah", "David"],
            correctAnswerIndex: 2,
            explanationHy: "Աստված պատվիրեց Նոյին տապան շինել, որպեսզի նա և իր ընտանիքը փրկվեն ջրհեղեղից։",
            explanationRu: "Бог повелел Ною построить ковчег, чтобы спасти свою семью и животных от потопа.",
            explanationEn: "God commanded Noah to build an ark to save his family and animals from the flood.",
            verseRefHy: "Ծննդոց 6:14",
            verseRefRu: "Бытие 6:14",
            verseRefEn: "Genesis 6:14"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞ր լեռան վրա կանգ առավ Նոյան Տապանը ջրհեղեղից հետո։",
            questionRu: "На каких горах остановился Ноев Ковчег после потопа?",
            questionEn: "Upon which mountains did Noah's Ark come to rest after the flood?",
            optionsHy: ["Սինա", "Արարատ", "Ձիթենյաց", "Թաբոր"],
            optionsRu: ["Синай", "Арарат", "Елеонская", "Фавор"],
            optionsEn: ["Sinai", "Ararat", "Mount Olivet", "Tabor"],
            correctAnswerIndex: 1,
            explanationHy: "Տապանը կանգ առավ Արարատի լեռների վրա (Ծննդոց 8:4)։",
            explanationRu: "Ковчег остановился на горах Араратских (Бытие 8:4).",
            explanationEn: "The ark came to rest upon the mountains of Ararat (Genesis 8:4).",
            verseRefHy: "Ծննդոց 8:4",
            verseRefRu: "Бытие 8:4",
            verseRefEn: "Genesis 8:4"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ սպանեց Գողիաթին պարսատիկով և քարով։",
            questionRu: "Кто победил великана Голиафа с помощью пращи и камня?",
            questionEn: "Who defeated the giant Goliath using a sling and a stone?",
            optionsHy: ["Սավուղը", "Սողոմոնը", "Դավիթը", "Սամսոնը"],
            optionsRu: ["Саул", "Соломон", "Давид", "Самсон"],
            optionsEn: ["Saul", "Solomon", "David", "Samson"],
            correctAnswerIndex: 2,
            explanationHy: "Երիտասարդ Դավիթը հավատով ելավ փղշտացի Գողիաթի դեմ և հաղթեց նրան Տիրոջ անունով։",
            explanationRu: "Молодой Давид выступил с верою против филистимлянина Голиафа и победил во имя Господа.",
            explanationEn: "Young David confronted Goliath in faith and defeated him in the name of the Lord.",
            verseRefHy: "Ա Թագավորաց 17:50",
            verseRefRu: "1 Царств 17:50",
            verseRefEn: "1 Samuel 17:50"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ ստացավ 10 Պատվիրանները Սինա լեռան վրա։",
            questionRu: "Кто получил 10 Заповедей на горе Синай?",
            questionEn: "Who received the 10 Commandments on Mount Sinai?",
            optionsHy: ["Աբրահամը", "Մովսեսը", "Հեսուն", "Ահարոնը"],
            optionsRu: ["Авраам", "Моисей", "Иисус Навин", "Аарон"],
            optionsEn: ["Abraham", "Moses", "Joshua", "Aaron"],
            correctAnswerIndex: 1,
            explanationHy: "Մովսեսը բարձրացավ Սինա լեռը և ստացավ տասը պատվիրանները Աստծո մատով գրված։",
            explanationRu: "Моисей взошел на Синай и принял скрижали с десятью заповедями от Бога.",
            explanationEn: "Moses ascended Mount Sinai and received the ten commandments inscribed by the finger of God.",
            verseRefHy: "Ելք 20:1-17",
            verseRefRu: "Исход 20:1-17",
            verseRefEn: "Exodus 20:1-17"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ էր Աստվածաշնչում ամենաիմաստուն թագավորը։",
            questionRu: "Кто был самым мудрым царем в Библии?",
            questionEn: "Who was the wisest king in the Bible?",
            optionsHy: ["Սավուղը", "Դավիթը", "Սողոմոնը", "Եզեկիան"],
            optionsRu: ["Саул", "Давид", "Соломон", "Езекия"],
            optionsEn: ["Saul", "David", "Solomon", "Hezekiah"],
            correctAnswerIndex: 2,
            explanationHy: "Աստված Սողոմոնին տվեց անգերազանցելի իմաստություն և հանճարեղ միտք։",
            explanationRu: "Бог даровал Соломону сердце мудрое и разумное, равного которому не было.",
            explanationEn: "God gave Solomon a wise and discerning heart greater than anyone before or after.",
            verseRefHy: "Գ Թագավորաց 3:12",
            verseRefRu: "3 Царств 3:12",
            verseRefEn: "1 Kings 3:12"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞ւմ վաճառեցին իր եղբայրները Եգիպտոսի ստրկության։",
            questionRu: "Кого братья продали в рабство в Египет?",
            questionEn: "Whom did his brothers sell into slavery in Egypt?",
            optionsHy: ["Բենիամինին", "Հովսեփին", "Հուդային", "Ռուբենին"],
            optionsRu: ["Вениамина", "Иосифа", "Иуду", "Рувима"],
            optionsEn: ["Benjamin", "Joseph", "Judah", "Reuben"],
            correctAnswerIndex: 1,
            explanationHy: "Հովսեփի եղբայրները նախանձից վաճառեցին նրան իսմայելացիներին 20 արծաթով։",
            explanationRu: "Братья Иосифа из зависти продали его каравану купцов за 20 серебреников.",
            explanationEn: "Joseph's brothers sold him out of jealousy to Midianite merchants for 20 pieces of silver.",
            verseRefHy: "Ծննդոց 37:28",
            verseRefRu: "Бытие 37:28",
            verseRefEn: "Genesis 37:28"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞ր մարգարեին կուլ տվեց մեծ կետ-ձուկը 3 օր ու 3 գիշեր։",
            questionRu: "Какого пророка поглотила большая рыба на три дня и три ночи?",
            questionEn: "Which prophet was swallowed by a great fish for 3 days and 3 nights?",
            optionsHy: ["Եսայի", "Հովնան", "Երեմիա", "Դանիել"],
            optionsRu: ["Исаия", "Иона", "Иеремия", "Даниил"],
            optionsEn: ["Isaiah", "Jonah", "Jeremiah", "Daniel"],
            correctAnswerIndex: 1,
            explanationHy: "Հովնանը փորձեց փախչել Նինվեից, բայց փոթորկից հետո հայտնվեց կետի փորում։",
            explanationRu: "Пророк Иона пытался уклониться от проповеди в Ниневии и провел три дня во чреве кита.",
            explanationEn: "Prophet Jonah fled from the Lord's calling to Nineveh and spent three days inside the fish.",
            verseRefHy: "Հովնան 2:1",
            verseRefRu: "Иона 2:1",
            verseRefEn: "Jonah 1:17"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞ր մարգարեին նետեցին առյուծների գուբը, բայց Աստված փակեց առյուծների բերանը։",
            questionRu: "Какого пророка бросили в ров ко львам, но Бог заградил пасть зверям?",
            questionEn: "Which prophet was thrown into the lions' den, but God shut the lions' mouths?",
            optionsHy: ["Եզեկիել", "Դանիել", "Ամովս", "Միքիա"],
            optionsRu: ["Иезекииль", "Даниил", "Амос", "Михей"],
            optionsEn: ["Ezekiel", "Daniel", "Amos", "Micah"],
            correctAnswerIndex: 1,
            explanationHy: "Դանիել մարգարեն հավատարիմ մնաց Աղոթքին և անվնաս մնաց առյուծների գբում։",
            explanationRu: "Даниил не перестал молиться истинному Богу и был спасен ангелом от львов.",
            explanationEn: "Daniel remained faithful in prayer and God sent His angel to shut the lions' mouths.",
            verseRefHy: "Դանիել 6:22",
            verseRefRu: "Даниил 6:22",
            verseRefEn: "Daniel 6:22"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ էր Իսրայելի առաջին թագավորը։",
            questionRu: "Кто был первым царем Израиля?",
            questionEn: "Who was the first king of Israel?",
            optionsHy: ["Դավիթը", "Սողոմոնը", "Սավուղը", "Հերովդեսը"],
            optionsRu: ["Давид", "Соломон", "Саул", "Ирод"],
            optionsEn: ["David", "Solomon", "Saul", "Herod"],
            correctAnswerIndex: 2,
            explanationHy: "Սամուել մարգարեն օծեց Սավուղին որպես Իսրայելի առաջին թագավոր։",
            explanationRu: "Пророк Самуил по повелению Бога помазал Саула первым царем Израиля.",
            explanationEn: "Prophet Samuel anointed Saul as the first king over Israel.",
            verseRefHy: "Ա Թագավորաց 10:1",
            verseRefRu: "1 Царств 10:1",
            verseRefEn: "1 Samuel 10:1"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Քանի՞ գլուխ ունի Սաղմոսների գիրքը։",
            questionRu: "Сколько глав (псалмов) содержит Книга Псалтирь?",
            questionEn: "How many chapters (psalms) does the Book of Psalms contain?",
            optionsHy: ["100", "120", "150", "180"],
            optionsRu: ["100", "120", "150", "180"],
            optionsEn: ["100", "120", "150", "180"],
            correctAnswerIndex: 2,
            explanationHy: "Սաղմոսարանը բաղկացած է 150 սաղմոսներից (կանոնական հաշվարկով)։",
            explanationRu: "Псалтирь содержит 150 вдохновенных молитвенных псалмов.",
            explanationEn: "The canonical Book of Psalms consists of 150 psalms.",
            verseRefHy: "Սաղմոսներ 150:6",
            verseRefRu: "Псалтирь 150:6",
            verseRefEn: "Psalm 150:6"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Ո՞ր մարգարեն հրեղեն կառքով երկինք համբարձվեց։",
            questionRu: "Какой пророк был вознесен на небо в огненной колеснице?",
            questionEn: "Which prophet was taken up to heaven in a chariot of fire?",
            optionsHy: ["Եղիսե", "Եղիա", "Եսայի", "Եզեկիել"],
            optionsRu: ["Елисей", "Илия", "Исаия", "Иезекииль"],
            optionsEn: ["Elisha", "Elijah", "Isaiah", "Ezekiel"],
            correctAnswerIndex: 1,
            explanationHy: "Եղիա մարգարեն հրեղեն կառքով և մրրիկով տարվեց երկինք։",
            explanationRu: "Пророк Илия был взят на небо в огненной колеснице с огненными конями в вихре.",
            explanationEn: "Prophet Elijah ascended into heaven in a chariot of fire with horses of fire.",
            verseRefHy: "Դ Թագավորաց 2:11",
            verseRefRu: "4 Царств 2:11",
            verseRefEn: "2 Kings 2:11"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞ր ծովը բաժանեց Մովսեսը Տիրոջ զորությամբ, որպեսզի ժողովուրդն անցնի։",
            questionRu: "Какое море расступилось по слову Моисея и силе Божьей для исхода народа?",
            questionEn: "Which sea parted through Moses by God's power for the Israelites to cross?",
            optionsHy: ["Մեռյալ ծովը", "Կարմիր ծովը", "Միջերկրական ծովը", "Գալիլեայի ծովը"],
            optionsRu: ["Мертвое море", "Красное (Чермное) море", "Средиземное море", "Галилейское море"],
            optionsEn: ["Dead Sea", "Red Sea", "Mediterranean Sea", "Sea of Galilee"],
            correctAnswerIndex: 1,
            explanationHy: "Կարմիր ծովի ջրերը բաժանվեցին, և Իսրայելի որդիներն անցան ցամաքով։",
            explanationRu: "Воды Чермного (Красного) моря расступились стеною, и народ прошел посуху.",
            explanationEn: "The waters of the Red Sea divided and the Israelites crossed on dry ground.",
            verseRefHy: "Ելք 14:21-22",
            verseRefRu: "Исход 14:21-22",
            verseRefEn: "Exodus 14:21-22"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Ո՞վ էր Աբրահամի խոստացված որդին, որին նա պատրաստ էր զոհաբերել Մորիա լեռան վրա։",
            questionRu: "Кто был обетованным сыном Авраама, которого он готов был принести в жертву на горе Мориа?",
            questionEn: "Who was Abraham's son of promise whom he was willing to sacrifice on Mount Moriah?",
            optionsHy: ["Իսմայելը", "Իսահակը", "Հակոբը", "Եսավը"],
            optionsRu: ["Измаил", "Исаак", "Иаков", "Исав"],
            optionsEn: ["Ishmael", "Isaac", "Jacob", "Esau"],
            correctAnswerIndex: 1,
            explanationHy: "Աստված փորձեց Աբրահամի հավատը Իսահակի միջոցով և տեղը խոյ տրամադրեց։",
            explanationRu: "Авраам явил абсолютную веру в послушании принести Исаака, но Бог предоставил овна.",
            explanationEn: "God tested Abraham's faith regarding Isaac and provided a ram caught in the thicket.",
            verseRefHy: "Ծննդոց 22:9-13",
            verseRefRu: "Бытие 22:9-13",
            verseRefEn: "Genesis 22:9-13"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ի՞նչ սնունդ էր իջնում երկնքից 40 տարի անապատում Իսրայելի համար։",
            questionRu: "Какая пища сходила с неба для насыщения народа Израиля в пустыне?",
            questionEn: "What bread rained from heaven to sustain the Israelites in the desert?",
            optionsHy: ["Մանանա", "Նուռ", "Խուրմա", "Գարի"],
            optionsRu: ["Манна", "Гранат", "Финики", "Ячмень"],
            optionsEn: ["Manna", "Pomegranate", "Dates", "Barley"],
            correctAnswerIndex: 0,
            explanationHy: "Աստված երկնքից տալիս էր մանանա՝ «հրեշտակների հացը»։",
            explanationRu: "Каждое утро Бог посылал с небес манну для пропитания народа.",
            explanationEn: "God rained down manna every morning to feed the people in the wilderness.",
            verseRefHy: "Ելք 16:15",
            verseRefRu: "Исход 16:15",
            verseRefEn: "Exodus 16:15"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Ո՞վ էր այն քաջ կինը, որը փրկեց իր ողջ հրեա ժողովրդին Համանի դավադրությունից։",
            questionRu: "Какая благочестивая царица спасла свой еврейский народ от истребления Аманом?",
            questionEn: "Which brave queen saved her people from Haman's plot of extermination?",
            optionsHy: ["Հռութը", "Եսթերը", "Դեբորան", "Աննան"],
            optionsRu: ["Руфь", "Есфирь", "Девора", "Анна"],
            optionsEn: ["Ruth", "Esther", "Deborah", "Hannah"],
            correctAnswerIndex: 1,
            explanationHy: "Եսթեր թագուհին ծոմապահությամբ և քաջությամբ կանգնեց թագավորի առաջ և փրկեց ժողովրդին։",
            explanationRu: "Царица Есфирь с постом и молитвой обратилась к царю и спасла соплеменников.",
            explanationEn: "Queen Esther risked her life, fasting and petitioning the king to save her people.",
            verseRefHy: "Եսթեր 4:16",
            verseRefRu: "Есфирь 4:16",
            verseRefEn: "Esther 4:16"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Ո՞վ էր աստվածաշնչյան այն արդար մարդը, որը համբերությամբ կրեց բոլոր փորձությունները և չմեղանչեց։",
            questionRu: "Какой праведник стойко перенес тяжелейшие испытания и потери, оставшись верным Богу?",
            questionEn: "Which righteous man endured immense suffering and loss while remaining faithful to God?",
            optionsHy: ["Հոբը", "Նոյը", "Ենոքը", "Լովտը"],
            optionsRu: ["Иов", "Ной", "Енох", "Лот"],
            optionsEn: ["Job", "Noah", "Enoch", "Lot"],
            correctAnswerIndex: 0,
            explanationHy: "Հոբ Երանելին փորձությունների մեջ ասաց. «Տերը տվեց, Տերն էլ առավ, օրհնյալ լինի Տիրոջ անունը»։",
            explanationRu: "Многострадальный Иов сохранил верность: «Господь дал, Господь и взял; да будет имя Господне благословенно!»",
            explanationEn: "Righteous Job persevered: «The Lord gave, and the Lord has taken away; blessed be the name of the Lord.»",
            verseRefHy: "Հոբ 1:21",
            verseRefRu: "Иов 1:21",
            verseRefEn: "Job 1:21"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ի՞նչ ազդանշան տվեց Աստված Նոյին որպես ուխտ, որ այլևս համաշխարհային ջրհեղեղ չի լինի։",
            questionRu: "Что Бог поставил на небе в знак вечного завета, что воды потопа больше не истребят землю?",
            questionEn: "What sign did God place in the sky as a covenant that waters would never again flood the earth?",
            optionsHy: ["Ծիածան", "Բևեռափայլ", "Արշալույս", "Գիսաստղ"],
            optionsRu: ["Радугу", "Северное сияние", "Утреннюю зарю", "Комету"],
            optionsEn: ["Rainbow", "Aurora", "Morning dawn", "Comet"],
            correctAnswerIndex: 0,
            explanationHy: "«Իմ ծիածանը դրի ամպերի մեջ, որպեսզի լինի ուխտի նշան Իմ և երկրի միջև»։",
            explanationRu: "«Я полагаю радугу Мою в облаке, чтоб она была знамением завета между Мною и между землею».",
            explanationEn: "«I set My rainbow in the cloud, and it shall be for the sign of the covenant between Me and the earth.»",
            verseRefHy: "Ծննդոց 9:13",
            verseRefRu: "Бытие 9:13",
            verseRefEn: "Genesis 9:13"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ ունեցավ երազում աստիճան, որը հասնում էր երկինք, և հրեշտակները բարձրանում ու իջնում էին։",
            questionRu: "Кто увидел во сне лестницу до небес, по которой восходили и нисходили ангелы Божьи?",
            questionEn: "Who dreamed of a ladder reaching to heaven with angels ascending and descending on it?",
            optionsHy: ["Հակոբը", "Իսահակը", "Աբրահամը", "Հովսեփը"],
            optionsRu: ["Иаков", "Исаак", "Авраам", "Иосиф"],
            optionsEn: ["Jacob", "Isaac", "Abraham", "Joseph"],
            correctAnswerIndex: 0,
            explanationHy: "Հակոբը Բեթելում տեսավ երկնային սանդուղքը և ստացավ Աստծո օրհնությունը։",
            explanationRu: "Иаков в Вефиле увидел небесную лестницу («Лествицу Иакова») и дал обет Богу.",
            explanationEn: "Jacob saw the stairway to heaven at Bethel and received God's blessing.",
            verseRefHy: "Ծննդոց 28:12",
            verseRefRu: "Бытие 28:12",
            verseRefEn: "Genesis 28:12"
        ),
        QuizQuestion(
            category: .oldTestament,
            difficulty: .hard,
            questionHy: "Ի՞նչ էր այն հրաշալի բույսը, որի միջից Աստված կանչեց Մովսեսին Հորեբ լեռան վրա։",
            questionRu: "Из какого горящего, но несгорающего куста Бог воззвал к Моисею на горе Хорив?",
            questionEn: "From what burning bush that was not consumed did God call Moses on Mount Horeb?",
            optionsHy: ["Անկեզ Մորենի", "Ձիթենի", "Արմավենի", "Մայրի"],
            optionsRu: ["Неопалимая Купина (терновый куст)", "Маслина", "Пальма", "Кедр"],
            optionsEn: ["Burning Bush (Thornbush)", "Olive tree", "Palm tree", "Cedar"],
            correctAnswerIndex: 0,
            explanationHy: "Մորենին վառվում էր կրակով, բայց չէր այրվում (Ելք 3:2)։",
            explanationRu: "Терновый куст горел огнем, но не сгорал — прообраз Богоматери и Божественной святости.",
            explanationEn: "The bush was on fire but did not burn up (Exodus 3:2).",
            verseRefHy: "Ելք 3:2",
            verseRefRu: "Исход 3:2",
            verseRefEn: "Exodus 3:2"
        ),
    ]  // конец массива
}
