import Foundation

extension QuizDatabase {
    // // MARK: - 2. ЕВАНГЕЛИЯ (GOSPELS)
    static let questionsGospels: [QuizQuestion] = [
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ո՞ր քաղաքում ծնվեց Հիսուս Քրիստոս։",
            questionRu: "В каком городе родился Иисус Христос?",
            questionEn: "In which city was Jesus Christ born?",
            optionsHy: ["Նազարեթ", "Երուսաղեմ", "Բեթղեհեմ", "Կափառնաում"],
            optionsRu: ["Назарет", "Иерусалим", "Вифлеем", "Капернаум"],
            optionsEn: ["Nazareth", "Jerusalem", "Bethlehem", "Capernaum"],
            correctAnswerIndex: 2,
            explanationHy: "Հիսուս ծնվեց Հուդայի Բեթղեհեմ քաղաքում, ինչպես մարգարեացվել էր Միքիա մարգարեի կողմից։",
            explanationRu: "Иисус родился в Вифлееме Иудейском, во исполнение древнего пророчества Михея.",
            explanationEn: "Jesus was born in Bethlehem of Judea, fulfilling the prophecy of Micah.",
            verseRefHy: "Մատթեոս 2:1",
            verseRefRu: "Матфея 2:1",
            verseRefEn: "Matthew 2:1"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ո՞ր գետում մկրտվեց Հիսուս Քրիստոս Հովհաննես Մկրտչի կողմից։",
            questionRu: "В какой реке крестился Иисус Христос от Иоанна Крестителя?",
            questionEn: "In which river was Jesus baptized by John the Baptist?",
            optionsHy: ["Եփրատ", "Տիգրիս", "Հորդանան", "Նեղոս"],
            optionsRu: ["Евфрат", "Тигр", "Иордан", "Нил"],
            optionsEn: ["Euphrates", "Tigris", "Jordan", "Nile"],
            correctAnswerIndex: 2,
            explanationHy: "Հիսուս մկրտվեց Հորդանան գետում, և Սուրբ Հոգին աղավնակերպ իջավ Նրա վրա։",
            explanationRu: "Иисус принял крещение в реке Иордан, и Дух Святой сошел на Него в виде голубя.",
            explanationEn: "Jesus was baptized in the Jordan River, and the Holy Spirit descended like a dove upon Him.",
            verseRefHy: "Մատթեոս 3:13-16",
            verseRefRu: "Матфея 3:13-16",
            verseRefEn: "Matthew 3:13-16"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Քանի՞ առաքյալ ընտրեց Հիսուսը։",
            questionRu: "Сколько ближайших апостолов избрал Иисус?",
            questionEn: "How many primary apostles did Jesus choose?",
            optionsHy: ["7", "10", "12", "70"],
            optionsRu: ["7", "10", "12", "70"],
            optionsEn: ["7", "10", "12", "70"],
            correctAnswerIndex: 2,
            explanationHy: "Հիսուս ընտրեց տասներկու աշակերտների, որոնց նաև առաքյալներ անվանեց։",
            explanationRu: "Иисус призвал двенадцать учеников, которых нарек Апостолами.",
            explanationEn: "Jesus called His twelve disciples, whom He also named apostles.",
            verseRefHy: "Ղուկաս 6:13",
            verseRefRu: "Луки 6:13",
            verseRefEn: "Luke 6:13"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞րն էր Հիսուսի կատարած առաջին հրաշքը։",
            questionRu: "Какое первое чудо совершил Иисус Христос?",
            questionEn: "What was the first miracle performed by Jesus?",
            optionsHy: ["Կույրի բժշկումը", "Ջուրը գինի դարձնելը Կանայում", "Հացերի բազմացումը", "Ղազարոսի հարությունը"],
            optionsRu: ["Исцеление слепого", "Претворение воды в вино в Кане", "Умножение хлебов", "Воскрешение Лазаря"],
            optionsEn: ["Healing the blind man", "Turning water into wine at Cana", "Multiplying loaves", "Raising of Lazarus"],
            correctAnswerIndex: 1,
            explanationHy: "Գալիլեայի Կանա քաղաքի հարսանիքում Հիսուսը ջուրը փոխակերպեց ընտիր գինու։",
            explanationRu: "На брачном пире в Кане Галилейской Иисус претворил воду в превосходное вино.",
            explanationEn: "At the wedding in Cana of Galilee, Jesus turned water into fine wine.",
            verseRefHy: "Հովհաննես 2:11",
            verseRefRu: "Иоанна 2:11",
            verseRefEn: "John 2:11"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Քանի՞ հացով և ձկով Հիսուսը կերակրեց 5000 մարդկանց։",
            questionRu: "Сколькими хлебами и рыбами Иисус накормил 5000 человек?",
            questionEn: "How many loaves and fish did Jesus use to feed the 5,000?",
            optionsHy: ["5 հաց և 2 ձուկ", "7 հաց և 3 ձուկ", "3 հաց և 5 ձուկ", "12 հաց և 2 ձուկ"],
            optionsRu: ["5 хлебов и 2 рыбы", "7 хлебов и 3 рыбы", "3 хлеба и 5 рыб", "12 хлебов и 2 рыбы"],
            optionsEn: ["5 loaves and 2 fish", "7 loaves and 3 fish", "3 loaves and 5 fish", "12 loaves and 2 fish"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուս օրհնեց 5 նկանակն ու 2 ձուկը, կերակրեց բազմությանը, և մնաց 12 լիքը կողով։",
            explanationRu: "Иисус благословил 5 хлебов и 2 рыбы, насытил 5000 человек и собрали 12 полных коробов.",
            explanationEn: "Jesus blessed five loaves and two fish, feeding 5,000 men with twelve baskets left over.",
            verseRefHy: "Մատթեոս 14:19-20",
            verseRefRu: "Матфея 14:19-20",
            verseRefEn: "Matthew 14:19-20"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Քանի՞ օր էր Ղազարոսը գերեզմանում, երբ Հիսուսը նրան հարություն տվեց։",
            questionRu: "Сколько дней Лазарь находился во гробе, прежде чем Иисус воскресил его?",
            questionEn: "How many days had Lazarus been in the tomb when Jesus raised him from the dead?",
            optionsHy: ["1 օր", "2 օր", "3 օր", "4 օր"],
            optionsRu: ["1 день", "2 дня", "3 дня", "4 дня"],
            optionsEn: ["1 day", "2 days", "3 days", "4 days"],
            correctAnswerIndex: 3,
            explanationHy: "Ղազարոսն արդեն չորս օրվա մեռյալ էր, երբ Հիսուսն ասաց. «Ղազարո՛ս, դո՛ւրս արի»։",
            explanationRu: "Лазарь был во гробе уже четыре дня, когда Господь воззвал: «Лазарь! иди вон».",
            explanationEn: "Lazarus had already been in the tomb four days when Jesus called: «Lazarus, come out!»",
            verseRefHy: "Հովհաննես 11:39-44",
            verseRefRu: "Иоанна 11:39-44",
            verseRefEn: "John 11:39-44"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .easy,
            questionHy: "Ո՞րն է Աստվածաշնչի ամենակարճ համարը։",
            questionRu: "Какой самый короткий стих во всей Библии?",
            questionEn: "What is the shortest verse in the entire Bible?",
            optionsHy: ["«Հիսուս լաց եղավ»", "«Աղոթեցեք»", "«Փառք Աստծո»", "«Սիրեցեք միմյանց»"],
            optionsRu: ["«Иисус прослезился»", "«Непрестанно молитесь»", "«Слава Богу»", "«Любите друг друга»"],
            optionsEn: ["«Jesus wept»", "«Pray continually»", "«Glory to God»", "«Love one another»"],
            correctAnswerIndex: 0,
            explanationHy: "«Հիսուս լաց եղավ» (Հովհաննես 11:35)՝ Ղազարոսի գերեզմանի մոտ։",
            explanationRu: "«Иисус прослезился» (Иоанна 11:35) у гробницы Своего друга Лазаря.",
            explanationEn: "«Jesus wept» (John 11:35) as He stood near the tomb of His friend Lazarus.",
            verseRefHy: "Հովհաննես 11:35",
            verseRefRu: "Иоанна 11:35",
            verseRefEn: "John 11:35"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞ր առակում է հայրը գրկաբաց ընդունում զղջացող որդուն։",
            questionRu: "В какой притче отец с любовью и всепрощением принимает вернувшегося сына?",
            questionEn: "In which parable does a father embrace and forgive his returning repentant son?",
            optionsHy: ["Անառակ որդու առակը", "Բարի սամարացու առակը", "Սերմնացանի առակը", "Տասը կույսերի առակը"],
            optionsRu: ["Притча о блудном сыне", "Притча о добром самарянине", "Притча о сеятеле", "Притча о десяти девах"],
            optionsEn: ["Parable of the Prodigal Son", "Parable of the Good Samaritan", "Parable of the Sower", "Parable of the Ten Virgins"],
            correctAnswerIndex: 0,
            explanationHy: "Անառակ որդու առակը ցույց է տալիս Երկնային Հոր անսահման ողորմությունն ու սերը։",
            explanationRu: "Притча о блудном сыне являет безграничную любовь и милосердие Небесного Отца к кающимся.",
            explanationEn: "The Parable of the Prodigal Son illustrates the boundless mercy and joy of the Heavenly Father.",
            verseRefHy: "Ղուկաս 15:11-32",
            verseRefRu: "Луки 15:11-32",
            verseRefEn: "Luke 15:11-32"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞վ օգնեց ավազակների ձեռքն ընկած վիրավոր մարդուն ճանապարհին։",
            questionRu: "Кто оказал милость и перевязал раны избитому разбойниками путнику?",
            questionEn: "Who showed mercy and bandaged the wounds of the man beaten by robbers?",
            optionsHy: ["Քահանան", "Ղևտացին", "Բարի Սամարացին", "Փարիսեցին"],
            optionsRu: ["Священник", "Левит", "Добрый Самарянин", "Фарисей"],
            optionsEn: ["The Priest", "The Levite", "The Good Samaritan", "The Pharisee"],
            correctAnswerIndex: 2,
            explanationHy: "Բարի Սամարացին խղճաց, բուժեց նրա վերքերը և հոգ տարավ նրա մասին իջևանատանը։",
            explanationRu: "Добрый Самарянин сжалился, перевязал раны, отвез в гостиницу и позаботился о нем.",
            explanationEn: "The Good Samaritan had compassion, bound his wounds, and provided for his recovery.",
            verseRefHy: "Ղուկաս 10:33-35",
            verseRefRu: "Луки 10:33-35",
            verseRefEn: "Luke 10:33-35"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .hard,
            questionHy: "Քանի՞ անգամ Պետրոսը ուրացավ Քրիստոսին նախքան աքաղաղի կանչելը։",
            questionRu: "Сколько раз апостол Петр отрекся от Христа, прежде чем пропел петух?",
            questionEn: "How many times did Peter deny Christ before the rooster crowed?",
            optionsHy: ["1 անգամ", "2 անգամ", "3 անգամ", "7 անգամ"],
            optionsRu: ["1 раз", "2 раза", "3 раза", "7 раз"],
            optionsEn: ["1 time", "2 times", "3 times", "7 times"],
            correctAnswerIndex: 2,
            explanationHy: "Պետրոսը երեք անգամ ասաց, որ չի ճանաչում Հիսուսին, ապա դառնորեն լաց եղավ։",
            explanationRu: "Петр трижды отрекся от Учителя, после чего вспомнил предсказание Христа и горько плакал.",
            explanationEn: "Peter denied knowing Jesus three times, and then went out and wept bitterly.",
            verseRefHy: "Մատթեոս 26:75",
            verseRefRu: "Матфея 26:75",
            verseRefEn: "Matthew 26:75"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞վ մատնեց Հիսուսին 30 արծաթով։",
            questionRu: "Кто предал Иисуса первосвященникам за 30 серебреников?",
            questionEn: "Who betrayed Jesus to the chief priests for 30 pieces of silver?",
            optionsHy: ["Հուդա Իսկարիովտացին", "Թովմասը", "Պիղատոսը", "Կայիափան"],
            optionsRu: ["Иуда Искариот", "Фома", "Понтий Пилат", "Каиафа"],
            optionsEn: ["Judas Iscariot", "Thomas", "Pontius Pilate", "Caiaphas"],
            correctAnswerIndex: 0,
            explanationHy: "Հուդա Իսկարիովտացին համբույրով մատնեց Ուսուցչին Գեթսեմանիի պարտեզում։",
            explanationRu: "Иуда Искариот предал Спасителя за 30 монет, указав на Него лицемерным целованием.",
            explanationEn: "Judas Iscariot betrayed the Lord for 30 silver coins with a kiss in Gethsemane.",
            verseRefHy: "Մատթեոս 26:14-15",
            verseRefRu: "Матфея 26:14-15",
            verseRefEn: "Matthew 26:14-15"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .hard,
            questionHy: "Ի՞նչ էր գրված Հիսուսի Խաչի վերնագրի տախտակին (ՏԻՏԼՈՍ)։",
            questionRu: "Какая надпись была начертана на дощечке над распятым Иисусом?",
            questionEn: "What inscription was placed on the placard above Jesus on the Cross?",
            optionsHy: ["«Հիսուս Նազովրեցի՝ Հրեաների Թագավոր»", "«Մարգարե Նազարեթից»", "«Աշխարհի Փրկիչ»", "«Որդի Դավթի»"],
            optionsRu: ["«Иисус Назорей, Царь Иудейский»", "«Пророк из Назарета»", "«Спаситель мира»", "«Сын Давидов»"],
            optionsEn: ["«Jesus of Nazareth, King of the Jews»", "«Prophet from Nazareth»", "«Savior of the World»", "«Son of David»"],
            correctAnswerIndex: 0,
            explanationHy: "Պիղատոսը գրեց եբրայերեն, հունարեն և լատիներեն՝ «Հիսուս Նազովրեցի՝ Թագավոր Հրեից» (INRI)։",
            explanationRu: "Пилат сделал надпись на трех языках: «Иисус Назорей, Царь Иудейский» (INRI).",
            explanationEn: "Pilate wrote the title in Hebrew, Greek, and Latin: «Jesus of Nazareth, King of the Jews».",
            verseRefHy: "Հովհաննես 19:19",
            verseRefRu: "Иоанна 19:19",
            verseRefEn: "John 19:19"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ո՞վ էր առաջինը, որ գնաց Հիսուսի գերեզմանը հարության առավոտյան և տեսավ հարուցյալ Տիրոջը։",
            questionRu: "Кто первым пришел ко гробу воскресшего Спасителя ранним утром?",
            questionEn: "Who was the first to arrive at Jesus' tomb on resurrection morning and see the risen Lord?",
            optionsHy: ["Մարիամ Մագդաղենացին", "Մարթան", "Սալոմեն", "Մարիամ Կղեոպասը"],
            optionsRu: ["Мария Магдалина", "Марфа", "Саломия", "Мария Клеопова"],
            optionsEn: ["Mary Magdalene", "Martha", "Salome", "Mary of Clopas"],
            correctAnswerIndex: 0,
            explanationHy: "Մարիամ Մագդաղենացին տեսավ դատարկ գերեզմանը և հարուցյալ Քրիստոսին։",
            explanationRu: "Мария Магдалина первой увидела отваленный камень и воскресшего Христа.",
            explanationEn: "Mary Magdalene came early to the tomb and was the first to see the risen Christ.",
            verseRefHy: "Հովհաննես 20:1-16",
            verseRefRu: "Иоанна 20:1-16",
            verseRefEn: "John 20:1-16"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .hard,
            questionHy: "Ո՞ր առաքյալը չհավատաց Քրիստոսի հարությանը, մինչև չտեսավ գամերի հետքերը Նրա ձեռքերին։",
            questionRu: "Какой апостол усомнился в воскресении Христа, пока лично не увидел раны от гвоздей?",
            questionEn: "Which apostle doubted Jesus' resurrection until he saw the nail marks in His hands?",
            optionsHy: ["Թովմասը", "Անդրեասը", "Փիլիպպոսը", "Բարդուղիմեոսը"],
            optionsRu: ["Фома", "Андрей", "Филипп", "Варфоломей"],
            optionsEn: ["Thomas", "Andrew", "Philip", "Bartholomew"],
            correctAnswerIndex: 0,
            explanationHy: "Թովմասն ասաց. «Տեր իմ և Աստված իմ», երբ տեսավ Հիսուսի խոցված կողն ու ձեռքերը։",
            explanationRu: "Фома воскликнул: «Господь мой и Бог мой!», увидев раны воскресшего Христа.",
            explanationEn: "Thomas confessed: «My Lord and my God!» after seeing Jesus' wounds.",
            verseRefHy: "Հովհաննես 20:27-28",
            verseRefRu: "Иоанна 20:27-28",
            verseRefEn: "John 20:27-28"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ի՞նչ աղոթք սովորեցրեց Հիսուսը Իր աշակերտներին Լեռան Քարոզում։",
            questionRu: "Какую молитву преподал Иисус Своим ученикам в Нагорной проповеди?",
            questionEn: "Which prayer did Jesus teach His disciples in the Sermon on the Mount?",
            optionsHy: ["«Հայր Մեր» (Տերունական աղոթք)", "«Սուրբ Աստված»", "«Հավատամք»", "«Փառք ի բարձունս»"],
            optionsRu: ["«Отче наш» (Молитва Господня)", "«Трисвятое»", "«Символ Веры»", "«Великое славословие»"],
            optionsEn: ["«The Lord's Prayer» (Our Father)", "«Trisagion»", "«Nicene Creed»", "«Gloria in Excelsis»"],
            correctAnswerIndex: 0,
            explanationHy: "Հիսուս ուսուցանեց Տերունական աղոթքը՝ «Հա՛յր մեր, որ երկնքում ես...»։",
            explanationRu: "Христос заповедал Молитву Господню: «Отче наш, сущий на небесах...».",
            explanationEn: "Jesus gave the model prayer: «Our Father in heaven, hallowed be Your name...».",
            verseRefHy: "Մատթեոս 6:9-13",
            verseRefRu: "Матфея 6:9-13",
            verseRefEn: "Matthew 6:9-13"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .hard,
            questionHy: "Ո՞ր հինկտակարանյան մարգարեները հայտնվեցին Հիսուսի Պայծառակերպության (Թաբոր լեռան) ժամանակ։",
            questionRu: "Какие ветхозаветные пророки явились во славе во время Преображения Господня на Фаворе?",
            questionEn: "Which Old Testament prophets appeared in glory during the Transfiguration of Jesus?",
            optionsHy: ["Մովսեսը և Եղիան", "Աբրահամը և Դավիթը", "Եսային և Երեմիան", "Նոյը և Դանիելը"],
            optionsRu: ["Моисей и Илия", "Авраам и Давид", "Исаия и Иеремия", "Ной и Даниил"],
            optionsEn: ["Moses and Elijah", "Abraham and David", "Isaiah and Jeremiah", "Noah and Daniel"],
            correctAnswerIndex: 0,
            explanationHy: "Մովսեսը (օրենքի խորհրդանիշ) և Եղիան (մարգարեների խորհրդանիշ) զրուցում էին Հիսուսի հետ։",
            explanationRu: "Моисей (представитель Закона) и Илия (представитель Пророков) беседовали с преобразившимся Спасителем.",
            explanationEn: "Moses and Elijah appeared in glory, talking with Jesus about His departure.",
            verseRefHy: "Մատթեոս 17:3",
            verseRefRu: "Матфея 17:3",
            verseRefEn: "Matthew 17:3"
        ),
        QuizQuestion(
            category: .gospels,
            difficulty: .medium,
            questionHy: "Ի՞նչ նվերներ բերեցին արևելքից եկած մոգերը մանուկ Հիսուսին։",
            questionRu: "Какие три дара принесли восточные волхвы-мудрецы родившемуся Богомладенцу?",
            questionEn: "What three gifts did the Magi bring to the infant Jesus?",
            optionsHy: ["Ոսկի, կնդրուկ և զմուռս", "Արծաթ, գինի և ձեթ", "Մետաքս, ադամանդ և հաց", "Մեղր, նուռ և խունկ"],
            optionsRu: ["Золото, ладан и смирну", "Серебро, вино и елей", "Шелк, драгоценности и хлеб", "Мед, гранат и фимиам"],
            optionsEn: ["Gold, frankincense, and myrrh", "Silver, wine, and oil", "Silk, jewels, and bread", "Honey, pomegranates, and incense"],
            correctAnswerIndex: 0,
            explanationHy: "Ոսկի՝ որպես Թագավորի, կնդրուկ (խունկ)՝ որպես Աստծո, և զմուռս՝ որպես մահկանացու Փրկչի։",
            explanationRu: "Золото как Царю, ладан как Богу, и смирну как Спасителю, грядущему на искупительную смерть.",
            explanationEn: "Gold as to a King, frankincense as to God, and myrrh for His burial.",
            verseRefHy: "Մատթեոս 2:11",
            verseRefRu: "Матфея 2:11",
            verseRefEn: "Matthew 2:11"
        ),
    ]  // конец массива
}
