import Foundation

extension QuizDatabase {
    // // MARK: - 3. НОВЫЙ ЗАВЕТ И АПОСТОЛЫ (NEW TESTAMENT)
    static let questionsNT: [QuizQuestion] = [
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ո՞վ էր Պողոս առաքյալը նախքան Քրիստոնեություն ընդունելը։",
            questionRu: "Кем был апостол Павел до своего обращения ко Христу?",
            questionEn: "Who was the Apostle Paul before his conversion to Christ?",
            optionsHy: ["Ձկնորս", "Սավուղ (հալածող)", "Մաքսավոր", "Քահանայապետ"],
            optionsRu: ["Рыбак", "Савл (гонитель христиан)", "Мытарь", "Первосвященник"],
            optionsEn: ["Fisherman", "Saul (persecutor of Christians)", "Tax collector", "High Priest"],
            correctAnswerIndex: 1,
            explanationHy: "Սավուղը հալածում էր եկեղեցին, մինչև Դամասկոսի ճանապարհին հանդիպեց Տեր Հիսուսին։",
            explanationRu: "Савл яростно преследовал христиан, пока на пути в Дамаск не встретил явившегося Христа.",
            explanationEn: "Saul persecuted the early Church until the risen Lord appeared to him on the Damascus road.",
            verseRefHy: "Գործք 9:3-5",
            verseRefRu: "Деяния 9:3-5",
            verseRefEn: "Acts 9:3-5"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ո՞ր քաղաքում Քրիստոսի հետևորդները առաջին անգամ կոչվեցին «Քրիստոնյաներ»։",
            questionRu: "В каком городе ученики Христа впервые стали называться «Христианами»?",
            questionEn: "In which city were the disciples first called «Christians»?",
            optionsHy: ["Երուսաղեմ", "Անտիոք", "Հռոմ", "Կորնթոս"],
            optionsRu: ["Иерусалим", "Антиохия", "Рим", "Коринф"],
            optionsEn: ["Jerusalem", "Antioch", "Rome", "Corinth"],
            correctAnswerIndex: 1,
            explanationHy: "Անտիոքում աշակերտները առաջին անգամ կոչվեցին Քրիստոնյաներ (Գործք 11:26)։",
            explanationRu: "В сирийской Антиохии верующие впервые получили имя «христиане».",
            explanationEn: "It was in Antioch that the disciples were first called Christians.",
            verseRefHy: "Գործք 11:26",
            verseRefRu: "Деяния 11:26",
            verseRefEn: "Acts 11:26"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ո՞վ էր Առաջին Քրիստոնյա Նահատակը (Նախասարկավագը)։",
            questionRu: "Кто был первым христианским мучеником (первомучеником и архидиаконом)?",
            questionEn: "Who was the first Christian martyr (protomartyr and archdeacon)?",
            optionsHy: ["Սուրբ Ստեփանոսը", "Սուրբ Պետրոսը", "Սուրբ Հակոբոսը", "Սուրբ Պողոսը"],
            optionsRu: ["Святой Стефан", "Святой Пётр", "Святой Иаков", "Святой Павел"],
            optionsEn: ["Saint Stephen", "Saint Peter", "Saint James", "Saint Paul"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Ստեփանոս Նախավկան քարկոծվեց Քրիստոսի վկայության համար՝ ներելով իրեն քարկոծողներին։",
            explanationRu: "Святой Стефан был побит камнями за исповедание веры, молясь: «Господи! не вмени им греха сего».",
            explanationEn: "Saint Stephen was stoned for witnessing to Christ, praying for his executioners.",
            verseRefHy: "Գործք 7:59-60",
            verseRefRu: "Деяния 7:59-60",
            verseRefEn: "Acts 7:59-60"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .easy,
            questionHy: "Ի՞նչ հրաշալի իրադարձություն տեղի ունեցավ Պենտեկոստեի (Հոգեգալուստի) օրը։",
            questionRu: "Какое великое событие произошло в день Пятидесятницы?",
            questionEn: "What miraculous event took place on the Day of Pentecost?",
            optionsHy: ["Սուրբ Հոգու Էջքը առաքյալների վրա", "Ջրհեղեղը", "Տաճարի կառուցումը", "Հիսուսի ծնունդը"],
            optionsRu: ["Сошествие Святого Духа на апостолов", "Великий потоп", "Освящение храма", "Рождество Христа"],
            optionsEn: ["Descent of the Holy Spirit on apostles", "Great Flood", "Temple dedication", "Nativity of Christ"],
            correctAnswerIndex: 0,
            explanationHy: "Սուրբ Հոգին իջավ հրեղեն լեզուներով, և առաքյալները սկսեցին խոսել տարբեր լեզուներով։",
            explanationRu: "Дух Святой сошел в виде огненных языков, наделив апостолов даром проповеди на всех языках.",
            explanationEn: "The Holy Spirit descended like tongues of fire, empowering the apostles to preach globally.",
            verseRefHy: "Գործք 2:1-4",
            verseRefRu: "Деяния 2:1-4",
            verseRefEn: "Acts 2:1-4"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ո՞րն է Նոր Կտակարանի վերջին գիրքը։",
            questionRu: "Какая последняя пророческая книга Нового Завета?",
            questionEn: "What is the final prophetic book of the New Testament?",
            optionsHy: ["Հայտնություն (Ապոկալիպսիս)", "Եբրայեցիներ", "Հուդա", "Գործք Առաքելոց"],
            optionsRu: ["Откровение Иоанна Богослова (Апокалипсис)", "Послание к Евреям", "Послание Иуды", "Деяния Апостолов"],
            optionsEn: ["Book of Revelation (Apocalypse)", "Hebrews", "Jude", "Acts of the Apostles"],
            correctAnswerIndex: 0,
            explanationHy: "Հովհաննես առաքյալի Հայտնությունը Պատմոս կղզում եզրափակում է Սուրբ Գիրքը։",
            explanationRu: "Книга Откровения святого Иоанна Богослова на острове Патмос завершает библейский канон.",
            explanationEn: "The Book of Revelation by John on Patmos concludes the Holy Scriptures.",
            verseRefHy: "Հայտնություն 22:20",
            verseRefRu: "Откровение 22:20",
            verseRefEn: "Revelation 22:20"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .hard,
            questionHy: "Ո՞ր գլխում է Պողոս առաքյալը գրել Սիրո հայտնի Օրհներգը («Եթե սեր չունենամ, ոչինչ եմ»)։",
            questionRu: "В какой главе апостол Павел воспел бессмертный Гимн Любви («Если я любви не имею, то я ничто»)?",
            questionEn: "In which chapter did Paul write the famous Hymn to Love («If I have not love, I am nothing»)?",
            optionsHy: ["Ա Կորնթացիս 13", "Հռոմեացիս 8", "Գաղատացիս 5", "Եփեսացիս 4"],
            optionsRu: ["1 Коринфянам 13", "Римлянам 8", "Галатам 5", "Ефесянам 4"],
            optionsEn: ["1 Corinthians 13", "Romans 8", "Galatians 5", "Ephesians 4"],
            correctAnswerIndex: 0,
            explanationHy: "«Սերը համբերող է, քաղցրաբարո է... Սերը երբեք չի անհետանում» (Ա Կորնթացիս 13:4-8)։",
            explanationRu: "«Любовь долготерпит, милосердствует... Любовь никогда не перестает» (1 Кор 13:4-8).",
            explanationEn: "«Love is patient, love is kind... Love never fails» (1 Corinthians 13:4-8).",
            verseRefHy: "Ա Կորնթացիս 13:1-13",
            verseRefRu: "1 Коринфянам 13:1-13",
            verseRefEn: "1 Corinthians 13:1-13"
        ),
        QuizQuestion(
            category: .newTestament,
            difficulty: .medium,
            questionHy: "Ի՞նչ մասնագիտություն ուներ Ղուկաս Ավետարանիչը։",
            questionRu: "Какую профессию имел святой евангелист Лука?",
            questionEn: "What profession did Saint Luke the Evangelist have?",
            optionsHy: ["Բժիշկ", "Զինվոր", "Ձկնորս", "Շինարար"],
            optionsRu: ["Врач", "Воин", "Рыбак", "Строитель"],
            optionsEn: ["Physician (Doctor)", "Soldier", "Fisherman", "Builder"],
            correctAnswerIndex: 0,
            explanationHy: "Պողոս առաքյալը նրան անվանում է «Ղուկասը՝ սիրելի բժիշկը» (Կողոսացիս 4:14)։",
            explanationRu: "Апостол Павел приветствует общину: «Приветствует вас Лука, врач возлюбленный» (Кол 4:14).",
            explanationEn: "Paul calls him «our dear friend Luke, the doctor» (Colossians 4:14).",
            verseRefHy: "Կողոսացիս 4:14",
            verseRefRu: "Колоссянам 4:14",
            verseRefEn: "Colossians 4:14"
        ),
    ]  // конец массива
}
